### ISSUE TITLE
[FEATURE] Provide a ref hook based API to apply animations.

### ISSUE THREAD

**Issue by youknowriad** [framer/motion#1039]
In the context of [Gutenberg](https://github.com/WordPress/gutenberg) (the WordPress block editor), we have an animation that triggers each time blocks in the editor are moved... This is the perfect use case for the "layout" prop of framer motion. 

While trying to implement it though, I had an issue related too the motion components: It's impossible for us to rely on `motion.div` and the like and it's also impossible for us to use the `motion` HoC to solve that. That's because we build the framework, but we don't control what block authors use (and they are in general just using the static elements). The way we solve that for other use-cases is by passing a "ref" to the block authors that they apply to their root element. 

So all of this to say, we'd love if there was a way to apply "layout animations" (and maybe all kind of animations)  using a hook that returns a "ref".

Was this considered before?

```js
const ref = useMotionRef( { layout: true } );

return <div ref={ref} />;
```

Thanks.

**Comment by mattgperry** [comment]
I do really like the idea but I'm afraid this would be impossible given the way things are at the moment. Each `motion` component represents a lot of dynamic functionality - animations, gestures, layout animations etc. Most of this functionality is provided by hooks, which for this idea is a good thing. However because hooks cant be used conditionally, we load a seperate component for each feature that loads its own hooks and returns null. This way we can render only the functionality we want.

To make things worse, because there's no `getSnapshotBeforeUpdate` lifecycle in hooks, the layout measurement component is a class component. So this layout functionality specifically is impossible to express using only hooks.

**Comment by youknowriad** [comment]
Thanks for the reply @mattgperry that make sense.
