### ISSUE TITLE
Having a build issue (Q/A)

### ISSUE THREAD

**Issue by curavcy** [framer/motion#1050]
Using Next,js to start, But cannot with these problem. Anyone recognize it before? 
Already deleted **package.lock.json** installed again. 
Using Node v14.15.5, Npm v6.14.11. 

```
Error: Package subpath './package.json' is not defined by "exports" in
    C:\Users\...\node_modules\framer-motion\package.json
    Code: ERR_PACKAGE_PATH_NOT_EXPORTED
```

**Comment by mattgperry** [comment]
Hmm this sounds daft (because where else is it reading exports from in the first place?) but looking at this: https://github.com/react-native-community/cli/issues/1168 if something defines exports, as we do now, package.json needs to have a specific export for it to be importable. I’ll take a look at this later today.

**Comment by mattgperry** [comment]
@curavcy can you try `4.0.1-rc.0` for me? I've attempted a fix
