### ISSUE TITLE
[BUG] offset values are very big when drag ends

### ISSUE THREAD

**Issue by danielo515** [framer/motion#1087]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

When you use the onDragEnd event handler, the values are much higher than what you actually dragged. On the following example you can see how by dragging it a few pixels it will report values over 50 px

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-path-drawing-drag-and-usetransform-forked-tgztw?file=/src/Example.tsx

**4. Steps to reproduce**

When you attach a dragEnd event listener, the values of the offset info object are bigger than what you actually dragged.
On the attached sandbox:
 1. Drag it a few pixels
 2. Open the console
 3. Check the values

**5. Expected behavior**

I expect the offset values to contain the amount of dragged distance, but for some reason the values are much much higher than what I actually dragged

**6. Video or screenshots**

If applicable, add a video or screenshots to help explain the bug.

**7. Environment details**

Chrome on MacOs

**Comment by bhollis** [comment]
I think what you're seeing is that the `offset` represents where the pointer is when the drag is released, not where the object being dragged is - the "rubber band" from the drag bounds is not being reflected in the offset.

**Comment by danielo515** [comment]
That may make sense.
But that means that the offset represents how much the pointer has been moved during drag? Or where the pointer is in reference to what? Because I can promise that moving the pointer just a few pixels gives me values over hundred.

**Comment by utileetdulce** [comment]
I can confirm that behaviour. It is reproducible with the provided CodeSandbox but it seems to appear only when using touch devices. E.g. a slight vertical drag to the bottom produces a info.offset.x of about 200px which seems to be more the point.x value. Since the documentation says that the offset is the "offset from the original pan event", is it possible that there is no "original pan event" for it to refer to?

**Comment by rATRIJS** [comment]
I can also confirm that this bug exists. I had this issue on an app I was building where a vertical scroll would sometimes trigger an effect caused by horizontal scroll although one didn't happen in real life.

Upon some investigation it seems that sometimes the `point` within `PanInfo` in the `onDragEnd` has zeroed coordinates which messes up the calculations for `offset` and `delta`.

As a quick hack fix I store the last value from `onDrag` event and use that in the `onDragEnd` instead as it seems to be correct there. I have not yet looked at the source code to see if there is a proper fix in code.

**Comment by mattgperry** [comment]
The offset reported is the pointer info. 

The drag offset is often different. To query this, you can use either the `onUpdate` prop and look at x/y, or provide them as motion values and track changes with `useMotionValueEvent`.
