### ISSUE TITLE
[BUG] boxShadow is recalculated everytime layout changes in  animateSharedLayout

### ISSUE THREAD

**Issue by weissleon** [framer/motion#1130]
Hi,
I am currently attempting to create an expandable card using **AnimateSharedLayout**.
My container card has a **box-shadow** applied, and everytime I toggle the expand button, I realized that the box-shadow is recalculated along with the layout change.

Also as a side note, I realized that if you hover the cursor on the expand button while the layout change animation is in process, for a brief moment, the point cursor changes to select cursor. Perhaps this is also related to the underlying cause associated with the original bug?

The code for the bug is provided below:
https://codesandbox.io/s/suspicious-wave-kd0m8?file=/src/App.tsx

What I believe to be an expected behavior is:
- Instead of being recalculated, the box-shadow values should remain consistent during the sharedLayout animation.

It was tested in **Chromium-based browsers** (Chrome&Edge), and **Samsung Browser**.

**Comment by mattgperry** [comment]
I think the cursor thing sounds like a browser issue. Perhaps something to do with using text for the button?  But the shadow, what's happening is because layout animations are performed using `transform`, we apply scale correction to certain values like `box-shadow` and `border-radius`. If we didn't, when closing the drop down you would end up with the shadow looking like this at the start of the animation:

![image](https://user-images.githubusercontent.com/7850794/117254379-3d07e680-ae40-11eb-9366-b838e27954a0.png)

Likewise, when opening the drop-down, the shadow would disappear, like this:

<img width="411" alt="Screenshot 2021-05-06 at 07 55 36" src="https://user-images.githubusercontent.com/7850794/117254559-74769300-ae40-11eb-98b1-f7030b4b29c2.png">

**Comment by weissleon** [comment]
Thank you for your explanation! 

I have one question and one issue.

**_1. Then is there any workarounds for this phenomenon, or should I go back to the  **AnimatePresence** way?_**

I am still having hope with the **AnimateSharedLayout** way because, in the official example: 
https://codesandbox.io/s/framer-motion-2-animating-shared-layouts-1cpd0?file=/src/App.js 
I found you set the **initial** property with borderRadius even though the corresponding property was already set in the CSS file.

To my understanding, the intention was similar to 
https://codesandbox.io/s/framer-motion-2-scale-correction-forked-qx1l1?file=/src/App.js ?

(BTW, in the official documentation, it is said that the intention was to correct the distortion, I could not observe any difference with and without the **initial={ ... }** line.)


**_2. I found a layout distortion inside the **container card** in the example code._**

Whenever I click the expand button, the purple line suddenly nudges a little to the right, then comes back.

However, I found that the issue depends on where I run the code. It works fine inside the codesandbox but not in other regular browsers.
I suspect it is similar to what happens in the official demo:
https://codesandbox.io/s/framer-motion-2-scale-correction-forked-qx1l1?file=/src/App.js

Whenever the shape is expanded, the pink circle is off from the center for a very brief time, then comes back. The intensity of the behavior again depended on the browsers, but this time it also appeared in the codesandbox.

**Comment by mattgperry** [comment]
Yeah you could set boxShadow via CSS rather than the style prop. Then it won’t be detected. Alternatively you can split the container into two elements, one that does the layout animation and another that applies the box shadow. 

Doing either will display the above visual distortion but that’s the trade off - the alternative is animating height itself but this should be slower than animating boxShadow. 

Your second point could be as layers pop on and off the GPU - maybe applying will-change: transform to all of them will keep them there?

**Comment by weissleon** [comment]
It is sad to hear that 🥺, but like you mentioned I guess it is a matter of trade-offs. 

Thank you for the kind replies! And I have to say I am in love with your library and its philosophy 😄
