### ISSUE TITLE
[BUG] staggerChildren works incorrectly when repeat property is used (?)

### ISSUE THREAD

**Issue by glomotion** [framer/motion#1146]
**1. Read the [FAQs](#faqs) 👇**
done!

**2. Describe the bug**
We want simply to animate 3 lines, one after another - and then repeats the whole animation again. 
Sequence should be:
```
line 1 draws across the screen
then line 2 draws across the screen
then line 3 draws across the screen
... repeat (go back to drawing in line 1) ...
```

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/example-framer-motion-bug-p0xwt?file=/src/index.js

**4. Steps to reproduce**
1. Go to codepen
2. See the lines animating all together

**5. Expected behavior**
Each line should animate by itself, one by one.

**7. Environment details**
Brave 1.24.82 & Firefox Developer edition 89.0b9 
on MacOs 11.3 (20E232)
framer-motion: 4.1.13

**Comment by r0ughnex** [comment]
### Update
- The issue was that the repeat animations happen immediately, eventually syncing all three lines ❗ 
- Adding the prop `repeatDelay` to the `childVariant` applied to `<motion.li />` fixes this issue ✔️  
- Each subsequent line animates for 1s, so the current line animation needs to repeat after +2s ✔️ 

```js
const childVariant = {
    left: { x: "-100%" },
    right: {
      x: "100%",
      transition: {
        ease: "linear",
        duration: 1,
        repeat: Infinity,
        repeatType: "loop",
        repeatDelay: "2",
      }
    }
  };
```

### Suggestion
It wasn't easy to find this in the API docs!  Perhaps an example could be added containing both `staggerChildren` and `delayChildren` used alongside with `repeat` for looping staggered animations.
