### ISSUE TITLE
[FEATURE] Supporting SVG gradientTransform Animations

### ISSUE THREAD

**Issue by PaulFidika** [framer/motion#1150]
It would be awesome if in the future framer-motion could animate the gradientTransform property of SVGs, like this:

```
const transition = { repeat: Infinity, repeatType: "mirror" }

 <motion.linearGradient
          id="gradient3"
          initial={{
            gradientTransform: "rotate(20)"
          }}
          animate={{
            gradientTransform: "rotate(180)"
          }}
          transition={{ ...transition, duration: 1 }}
        >
...
</ motion.linearGradient>
```

What this SHOULD do is create an animation that rotates the linear gradient from 20 degrees to 180 degrees back and forth infinitely, but currently this code does a 20-degree rotation initially and then never animates anything. Either I'm not understanding how to implement this correctly or framer-motion simply doesn't support gradientTransform animations yet.

Thanks!

**Comment by KirdesMF** [comment]
it could be an issue the value is animating but it renders `gradient-transform` instead of `gradientTransform`

![image](https://user-images.githubusercontent.com/54989552/118345366-4f66dc00-b534-11eb-8db2-4358b5023832.png)


I made a sandbox so you can check. and I give you some workaround.

https://codesandbox.io/s/framer-motion-svg-gradient-yze4g?file=/src/App.tsx

I did not try via the style object

**Comment by KirdesMF** [comment]
ok I think I've found the issue.

here it checks if the svg element attribute should be camelcase or not base on an Array

https://github.com/framer/motion/blob/c2edde914a23254459778f107d506f26bb1038f0/src/render/svg/utils/render.ts

if not the attribute the camel to dash

and here the list of attributes

https://github.com/framer/motion/blob/c2edde914a23254459778f107d506f26bb1038f0/src/render/svg/utils/camel-case-attrs.ts
