### ISSUE TITLE
[BUG] breaking changes 3.10.0 to 3.10.1

### ISSUE THREAD

**Issue by RayLuxembourg** [framer/motion#1171]
Side menu example stops working as expected from version 3.10.1.
It last worked as expected on version 3.10.0, anything above 3.10.0 is breaking.
Use the sandbox to switch between versions and check the animation.
[Sandbox](https://codesandbox.io/s/framer-motion-side-menu-forked-ek50p?file=/package.json:218-224)

**Comment by rbourdon** [comment]
I've run into this issue in my own project. To be more specific, the problem is including separate transitions for specific value inside a transition object appears to break staggerChildren. Check out [this fixed sandbox](https://codesandbox.io/s/framer-motion-side-menu-forked-dz8ys?file=/src/MenuItem.tsx), where the only change I made was to apply the same transition to all values on the menu item.
