### ISSUE TITLE
[BUG] Sharp transition during height animation

### ISSUE THREAD

**Issue by present-g** [framer/motion#1462]
**Describe the bug**

I need to animate the height from 0 to 'auto', the animation scene is calculated incorrectly, and when 'auto' appears, there is a jump

**IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/eager-silence-6cpkd0?file=/src/App.js

**Steps to reproduce**

1. Open the page
2. Look at the animation
3. You can use the "Toggle" button for easy replay

The problem is only when opening ...

**Expected behavior**

I need a smooth, jump-free animation with lots of components inside

**Comment by thexpand** [comment]
The reason why this happens is because of the padding on the animated element. Try eliminating the padding by adding a nested element (an inner container) and put the padding on that inner container. Then, animate the parent container - without the padding on the animated element, there shouldn't be that jumpy behavior.

**Comment by merlindru** [comment]
@thexpand I'm doing exactly that, but the jump still persists

**Comment by thexpand** [comment]
@merlindru Probably it would be best if you would provide a reproducible example with your specific use-case, e.g. in CodeSandbox.

**Comment by ervinpiol** [comment]
In my case I use <br /> for the space

**Comment by dev-frid** [comment]
Experiencing this as well - height animates inconsistently regardless of padding.
It animates the first time, any subsequent height changes do not animate. The only way to see the animation is to quickly collapse and expand the container, which causes the animation to play from the middle.
Reproduction:

```
<div>
 {/* Expanded content */}
      <AnimatePresence>
        {expanded && (
          <motion.div
            initial={{ height: 0 }}
            animate={{ height: "auto" }}
            exit={{ height: 0 }}
            transition={{ duration: 0.3, ease: "easeInOut" }}
            className={twMerge(
              "overflow-hidden",
              isSkeleton ? "bg-transparent" : "bg-[#123585] bg-opacity-20"
            )}
          >
            (content...)
          </motion.div>
        )}
      </AnimatePresence>
</div>

**Comment by ianpaschal** [comment]
I think this is still an issue. I've been experiencing the same using the latest version 11.11.9 of framer-motion.

My use-case is slightly different, but I believe the Codesandbox above still very accurately captures it.

I had a form with elements I wanted to hide and show. The form was a flexbox so of course once the element animates its height down to 0, the double `gap` between the element before the animated one, and the one after the animated one, jumps down to 0.

It would be nice if that was handled out of the box, but I do understand the limitation there, so an obvious work-around is what @thexpand proposes: (set the flex `gap` to 0, and) use padding inside the element. This way the animated element _and its spacing_ are both removed in the animation.

That being said, that doesn't work. Instead the behavior is still identical to what is in the Codesandbox above, where the padding "jumps" at the end of the animation (in my case out rather than in, in the sandbox, but almost certainly having the same root cause).

**Comment by kamrannazir901** [comment]
**Solution**

- When you apply transition on height then you cannot have padding on that element. [Otherwise no smooth transition]

- You need to wrap inner content with another div and give padding to it. and apply height transition to outer div

**_Example is here_**

```
 <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ duration: 0.5 }}
            id={`faq${id}`}
            role="region"
            aria-labelledby={`faq-button${id}`}
          >
            <div className="px-4 py-2">
              {answers.map((item, i) => (
                <p key={i}>
                  {i + 1}. {item}
                </p>
              ))}
            </div>
          </motion.div>
        )}
```
