### ISSUE TITLE
[BUG] scrollIntoView is blocked while animating presence after v6.3.8

### ISSUE THREAD

**Issue by mattp0123** [framer/motion#1593]
**2. Describe the bug**

As titled. I think it's related to this pull request: https://github.com/framer/motion/pull/1561

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/scroll-into-view-while-animating-b6wmqt?file=/src/App.tsx

**4. Steps to reproduce**

1. Click any todo inside the scroll area. The todo won't scroll into view.
2. Change the version of framer-motion to v6.3.7 and click any todo again. The todo will scroll into view.

**5. Expected behavior**

The todo should scroll into view after it's clicked.

**Comment by mattgperry** [comment]
I'm not overly sure how that PR could have affected this (even though it clearly is the culprit). 

I think it would be a preferred pattern to do the scroll after measurements have been completed, via an effect, rather than before setting state:

```javascript
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (props.isActive) {
      ref.current?.scrollIntoView({
        behavior: "smooth",
        block: "start"
      });
    }
  }, [props.isActive]);
``` 

https://codesandbox.io/s/scroll-into-view-while-animating-forked-5d79u8?file=/src/App.tsx:298-515

Given that this is possible and there's some difficult DOM interactions at play here this will probably be a wontfix for the time being.
