### ISSUE TITLE
[BUG] `staggerChildren` does not work when rerendering parent

### ISSUE THREAD

**Issue by WestBrian** [framer/motion#1633]
**2. Describe the bug**

When rerendering the parent staggering the children does not reanimate them.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[Codesandbox](https://codesandbox.io/s/quizzical-tesla-3bwj48?file=/src/App.tsx)

**4. Steps to reproduce**

Click on the refresh button to see it working as expected. Click on the toggle button to see it not working.

**5. Expected behavior**

I would expect because the parent is being removed and readded that it would go through the mount animations again and thus stagger the children.

**Comment by mattgperry** [comment]
The problem here is as far as React is aware, nothing has changed except the `innerText` of the `li` items. So there's nothing to animate.

To fix, pass a unique `key` prop to each `ul`. This will let React know that these are actually new components.

https://codesandbox.io/s/focused-rgb-yye805?file=/src/App.tsx
