### ISSUE TITLE
[BUG] Auto import not working for `motion` import

### ISSUE THREAD

**Issue by samselikoff** [framer/motion#1646]
I've noticed VSCode's auto import feature doesn't work for the `motion` export, while it works for every other API. I'm motivated to fix this but wanted to ask here first in case there's some known/specific reason it's not working.

If not, can I help out?

Thanks!

**Comment by mattgperry** [comment]
I don't think there's anything we can do here to change this, there's nothing special about the export as far as I know. I feel like VSCode imports etc have been gradually degrading over the last year and as we haven't changed anything in this area my assumption is VSC.

**Comment by FunctionDJ** [comment]
My guess is that it's because `motion` itself is not a React component.
- `motion` is not a function that returns `ReactNode`, it's a function for purposes outside JSX and it has properties for the motion elements like `motion.span`
- it doesn't start with an uppercase letter, which may affect the intellisense / autocomplete in JSX too because React components usually start with an uppercase letter

I have seen other libraries switch to explicit / individual / manual exports to solve similar issues (don't remember which one though) which would mean you'd import and use `MotionSpan` instead of importing `motion` and using `motion.span`.

Of course this would be a breaking change and probably requires new code-gen in the library to automatically generate all the different components for each HTML/JSX base element.
