### ISSUE TITLE
[BUG] whileHover doesn't animate back to int value from percent value

### ISSUE THREAD

**Issue by hennessyevan** [framer/motion#181]
**Describe the bug**
Width gets stuck at 100% when hovering in a basic example

**To Reproduce**
1. Visit codesandbox link
2. hover over the black div for more than a few seconds
3. When you leave hover it stays at 100%

**Screencap**
![Screen Recording 2019-07-10 at 3 13 16 PM](https://user-images.githubusercontent.com/16711653/60997785-a5114280-a325-11e9-8503-69a7a63d5c01.gif)

**Expected behavior**
It should animate back to the initial width on mouse out.

**Codesandbox**
https://codesandbox.io/s/variants-k9vfb

**Desktop (please complete the following information):**
 - OS: macOS mojave
 - Browser chrome
 - Version 75

**Comment by Andarist** [comment]
It's because the width is set to "100%" [here](https://github.com/framer/motion/blob/6eef683eed810f2bc9800c4c746130829ae75f87/src/animation/ValueAnimationControls.ts#L216) when animation ends (origin of this set is [here](https://github.com/framer/motion/blob/6eef683eed810f2bc9800c4c746130829ae75f87/src/animation/ValueAnimationControls.ts#L514)). And later values are being "restored" onHoverEnd from that set value [here](https://github.com/framer/motion/blob/6eef683eed810f2bc9800c4c746130829ae75f87/src/animation/ValueAnimationControls.ts#L377).

**Comment by hennessyevan** [comment]
Thanks for that explanation @Andarist, that makes sense. Just to be clear this **is** a bug right? This is the only thing keeping me moving from react-pose at the moment, interested on what the path forward would be.

**Comment by Andarist** [comment]
Yes, this is a bug. I’ve just debugged this in hope to preparing a fix but it ended up to be more difficult than i was prepared for. It was my first dive into this codebase and i dont know yet how all connects together. Nevertheless i believe my findings were good so ive wrote it down here so somebody could pick it up from here.
