### ISSUE TITLE
[BUG] useSpring effect was broken after upgrading to v7.6.18.

### ISSUE THREAD

**Issue by ysj151215** [framer/motion#1814]
I wrote a macOS dock style animation and worked perfectly before. But it was broken since v7.6.18 because of the removal of 'popmotion'? Here are the demos.

Before: https://stackblitz.com/github/ysj151215/big-sur-dock/
After: https://stackblitz.com/github/ysj151215/big-sur-dock/tree/develop

If I hover any square element inside the dock, then move the cursor outside and keep moving, the animation will look so slow, even without moving.

**Comment by jose-codegourmet** [comment]
oh my god I thought it was just me. can confirm useSpring is behaving like linear

**Comment by rosszurowski** [comment]
I ran into this too. In my case, adding `type: "spring"` as a property to the spring configuration fixed it.

I'm not even sure how I stumbled across this — I think I've added the same rule to various animations based on the [motion.dev](https://motion.dev) library and just tried it out here. I suspect this is an oversight and that `useSpring` should imply `type: "spring"` instead of requiring users to specify it.

In the case of your repo, updating line 17 of `components/dock/DockItem.jsx` to include the following property fixed it in my testing:

```diff
const spring = useSpring(48, {
+   type: "spring",
    damping: 10,
    stiffness: 150,
    mass: 0.01,
  })
```

**Comment by ysj151215** [comment]
> I ran into this too. In my case, adding `type: "spring"` as a property to the spring configuration fixed it.
> 
> I'm not even sure how I stumbled across this — I think I've added the same rule to various animations based on the [motion.dev](https://motion.dev) library and just tried it out here. I suspect this is an oversight and that `useSpring` should imply `type: "spring"` instead of requiring users to specify it.
> 
> In the case of your repo, updating line 17 of `components/dock/DockItem.jsx` to include the following property fixed it in my testing:
> 
> ```diff
> const spring = useSpring(48, {
> +   type: "spring",
>     damping: 10,
>     stiffness: 150,
>     mass: 0.01,
>   })
> ```

Thank you Ross! You saved my time. 🥳

**Comment by rosszurowski** [comment]
I think this issue warrants a fix from the framer-motion library even if we have a workaround, so I added #1822 to track implementing that.
