### ISSUE TITLE
[BUG] useScroll, if the content of the page is not enough for scroll, progress-bar is initialized.

### ISSUE THREAD

**Issue by caushcani** [framer/motion#1848]
HI there,
Im trying to implement usScroll on some pages, so there might be not enough content for page to 'scroll'...

Just forked your codesandbox example from doc:
Codesandbox link : https://codesandbox.io/s/framer-motion-usescroll-forked-i6gmce?file=/src/components/LoremIpsum.tsx

![image](https://user-images.githubusercontent.com/75629280/209474353-2be40c53-200f-487a-bd40-78c71b97bbed.png)

**Comment by mattgperry** [comment]
I think it’s as true that the page hasn’t scrolled as it is the page has scrolled fully. So defaulting to 1 vs 0 is a decision rather than a bug that ensures that no content remains hidden if the content isn’t long enough to allow scrolling. 

Perhaps it’s possible to allow a fallback value in these situations

**Comment by alexredder** [comment]
I seem to have a similar issue (although i have a long page - so scrolling is possible)
Could you detail on how to ensure the default is 0? - also console.logging the scrollYProgress is NaN.. 
:/ @mattgperry thanks for any advice

**Comment by mattgperry** [comment]
Closing as `wontfix` as I think it's more true that scrolling as completed than hasn't.
