### ISSUE TITLE
[FEATURE] dragElastic bounds

### ISSUE THREAD

**Issue by sami616** [framer/motion#190]
It would be great to be able to define how much 'elasticity' to apply to each `dragConstraint` edge using `dragElastic`

ie- `dragElastic={{ top: 0, bottom: 0.5 }}`

Trying to limit drag to only down in this demo: https://codesandbox.io/s/stoic-violet-h3bwn

**Comment by InventingWithMonster** [comment]
Yeah I think this would be a cool feature. I'd accept a PR on this if anyone wants to give it a shot!

**Comment by natemoo-re** [comment]
Rather than accepting a constraint-like object, could dragElastic accept a MotionValue? That could cover this use case and others. My use-case is to disallow overdrag past certain coordinates.

To that end, on a fork I was able to get dragElastic to read a MotionValue. But I ran into some glitchy behavior... Since a dragElastic of 0 restricts target movement to dragConstraints, setting dragElastic to 0 while a target is outside of its dragConstraints causes rapid position jumping.

Conceptually I guess I was thinking of dragElastic as a “dragResistance” type value rather than something spring-based.

@InventingWithMonster any thoughts on a path forward here? I’m happy to work on a PR!

**Comment by vdjurdjevic** [comment]
Any news on this?

**Comment by vdjurdjevic** [comment]
@InventingWithMonster I can submit pull request for this if you agree?

**Comment by sami616** [comment]
Hi all, i wondered if there was a work around for this in the time being? Im building a drawer component which i want users to be able to drag to close, it would be great to disable dragging in a particular direction!

**Comment by vdjurdjevic** [comment]
@sami616 The only workaround I found is to use react-spring :D I submitted a pull request for this, but got no response at all, not sure if it will be considered.
