### ISSUE TITLE
[BUG] positionTransition animation delayed when children exit

### ISSUE THREAD

**Issue by jessejanderson** [framer/motion#215]
**Describe the bug**
When `AnimatePresence` children unmount, the exit animation happens to completion before positionTransition animations take place. When new children mount, no such delay exists.

**To Reproduce**
1. Create basic example with `AnimatePresence` parent and `<motion.*>` children.
```
<AnimatePresence>
  <motion.div />
  <motion.div />
</AnimatePresence>
```
2. Add animation props to `<motion.div>` children
```
<motion.div
  animate={{ opacity: 1 }}
  initial={{ opacity: 0 }}
  exit={{ opacity: 0 }}
  key={uniqueKey}
  positionTransition
/>
```
3. Create a way to add/remove `<motion.div>` children.
```
<button onClick={handleAdd}>Add Child</button>

<AnimatePresence>
  <motion.div onClick={handleRemove} {...} />
</AnimatePresence>
```
4. Observe that when adding a child, all animations (opacity and position) happen simultaneous, but when removing a child, opacity/exit transitions happen first, and then position animations.

See example: https://codesandbox.io/s/framer-motion-reorder-animation-rlojg

**Expected behavior**
All animations happen simultaneously unless otherwise specified via delay prop, etc.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version 75.0.3770.142

**Comment by InventingWithMonster** [comment]
I'm not sure I understand exactly the problem here, maybe the snapping of the parent is confusing things.

If you keep the parent static between renders by changing `body` to:

```css
  justify-content: flex-start;
  align-items: flex-start;
```

Does the bug as you perceive it still occur?

The reason for this is `positionTransition` works when the offset of a component relative to its nearest-positioned parent changes **as the result of a render**. But if the parent itself is also moving then that also needs a `positionTransition` of its own.

However this is complicated with `AnimatePresence` because the parent component only really moves relative to the document once the exiting children are removed. The re-render to do this only happens **locally** within `AnimatePresence`. So the parent isn't informed.

We are talking about a component that will allow `AnimatePresence` to communicate changes within it back up the tree. So something along the lines of:

```
<LayoutContext>
  <motion.ul positionTransition>
    <AnimatePresence>
          <motion.li
            animate={{ opacity: 1 }}
            initial={{ opacity: 0 }}
            exit={{ opacity: 0 }}
            key={background}
            positionTransition={spring}
          />
    </AnimatePresence>
  </motion.ul>
</LayoutContext>
```

Will animate the parent smoothly even when children are removed.

**Comment by colepeters** [comment]
> The problem with doing it this way is you have to "pop out" the elements from their flow using `position: absolute` and manually setting their size and measurements. This is actually something you could do yourself via the style tag but after trying to implement a general solution I don't personally believe there's a way of achieving this that isn't bespoke to a specific design.

@InventingWithMonster sorry to bring up an old issue but wondering if you could elaborate on this? I'm facing the same issue the OP was, and if there's a way to work around it I'd love to give it a try. I'm just not sure I understand what needs to be done to achieve the desired effect based on your description.

**Comment by InventingWithMonster** [comment]
I’m gonna look into this as part of Framer Motion 2 and AnimateSharedLayout

**Comment by colepeters** [comment]
@InventingWithMonster That would be phenomenal! Please remind me to send you a cake if this makes it into the release! 😄

**Comment by colepeters** [comment]
@InventingWithMonster Just following up — I've updated to to 2.0 and notice this staggered exit/smooth entrance issue is still around. Is it something you're still looking into, or is it fixed and I'm just not implementing it properly?

**Comment by tgdn** [comment]
Any news on this issue?

**Comment by vladtihonovskiy** [comment]
Hi, @colepeters.
Did you find a solution? 
Because looks like the issue closed but I also get this problem

**Comment by justinpeake** [comment]
Also getting this problem.
