### ISSUE TITLE
[BUG] Cannot read properties of null (reading 'start')

### ISSUE THREAD

**Issue by galvin96** [framer/motion#2167]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

In the `motion/packages/framer-motion/src/animation/utils/is-animation-controls.ts` file, variable `v` can be null. So we can't get start of that variable.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[https://codesandbox.io/s/dry-sound-hvcyno?file=/src/App.js](https://codesandbox.io/s/dry-sound-hvcyno?file=/src/App.js)

**4. Steps to reproduce**

1. Go to CodeSandBox
2. Click on 'Click here'
3. See error

**5. Expected behavior**

check out the console

**Comment by galvin96** [comment]
I fixed that problem, could you give me permission to push my commit?

**Comment by tomfinney** [comment]
had this issue pop up for me the other day. there was some naive typing on my part passing down null instead of undefined and, unless i'm missing something, some naive typing in framer letting you pass in null when null isn't expected and breaks

```
export function isAnimationControls(v?: unknown): v is AnimationControls {
    return typeof v === "object" && typeof (v as any).start === "function"
}
```

this check should probably look to exclude null like `return typeof v === "object" && v !== null && typeof (v as any).start === "function"`? but if null is not meant to be allowed at all, maybe some type def should be modified too?

**Comment by a-rbsn** [comment]
I've also just encountered this error after updating an older project — the project worked fine before, will update here if I find out why it's happening in my case — I can't find any reference to animation controls in my next js directories.

**Comment by a-rbsn** [comment]
Yes, I was using a seperate library for detecting whether the element was in the viewport and returning a null to `animate=` if not, had to replace a `{}` instead to regain the functionality.
