### ISSUE TITLE
[BUG] <motion.div> ignores "position: fixed" on children 

### ISSUE THREAD

**Issue by laripereira14** [framer/motion#2201]
**1. Describe the bug**

I have a <ParentComponent> that takes up the whole page, absolute positioned with 10 of z-index. Inside, I have <ChildComponent> with a fixed header and a fixed footer. Wrapping <ParentComponent> in a <motion.div> breaks the elements in <ChildComponent> that have "position: fixed". 
I'm not sure if this is the intented behavior, but I can't seem to find a way to make it work.

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/p/sandbox/smoosh-wave-xk9l5k

**3. Steps to reproduce**

1. Go to the sandbox
2. On SlideUp.tsx, change this piece of code:

```
<motion.div
          className="container"
          variants={containerVariants}
          initial="initial"
          animate="animate"
          exit="exit"
>
          {children}
</motion.div>
```

3. To this one:
```
 <div className="container">
          {children}
    </div>
```
4. See error; it works when <motion.div> isn't used.

**4. Expected behavior**

The fixed elements should stay fixed.

**Comment by tkonopka** [comment]
Hi @laripereira14 . After the container finishes its animation, it retains a `translateY(0%)` transform, and this prevents the header/footer child elements from 'sticking'. Note sure if this is intended either. In any case, as a workaround, you can add a `transitionEnd` with `y: 0` to your animation.

https://codesandbox.io/p/sandbox/nifty-ptolemy-whp9d9

(In this sandbox, the footer jumps slightly at the end. That's because of the horizontal scrollbar. The jump would disappear if you can avoid creating the scrollbar).

**Comment by laripereira14** [comment]
@tkonopka This works nicely, thank you so much!

**Comment by laripereira14** [comment]
@tkonopka This works nicely, thank you so much!
