### ISSUE TITLE
[FEATURE] Animation between 359° and 0°

### ISSUE THREAD

**Issue by ladvoc** [framer/motion#2356]
I am building a compass component which accepts an `angle` prop in the range [0, 360°). Based on this angle, a needle animates to point in that direction. However, I have found the animation behavior is not what I would expect in this case.

Say for example the current angle is 359° and then the angle changes to 45°. In this situation, I would like the rotation of the needle to animate in a clockwise fashion from 359° to 45° since this is the shortest distance around the circle to reach the target; in practice, the needle travels counter-clockwise towards back around the circle towards its target.

So far, I have not discovered a way to achieve this effect. I can imagine a new transition option that would instruct Framer motion to dynamically choose the direction of movement when animating rotation properties based on the shortest distance around the circle:
```jsx
<motion.path 
      animate={{ rotate: props.angle }} 
      transition={{ rotation: "shortestDistance" }}
      stroke="black"
      d="..." />
```
Is there an existing feature I have overlooked that can achieve this effect?

**Comment by damnsamn** [comment]
This would be in line with standard CSS behaviour - positive changes will result in clockwise motion, and negative changes will result in anti-clockwise motion. Rather than animating between `359` and `45` (ie. a *negative* change), you should be animating between `359` and `404` (a *positive* change)

https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotate#a

**Comment by mattgperry** [comment]
Great explaination @damnsamn !
