### ISSUE TITLE
[BUG] Exit animation doesn't work

### ISSUE THREAD

**Issue by nicitaacom** [framer/motion#2384]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

When I click 'next' button I see no exit animation
```tsx
 <motion.div
                initial={{ translateX: "-100%" }}
                animate={{ translateX: ["100%", "0%"] }}
                exit={{ translateX: "-100%" }}
 ``` 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
codesandbox doesn't work - make git clone
https://github.com/nicitaacom/14_portfolio/blob/issue-framer-motion2/app/appointment/page.tsx
93 line

**4. Steps to reproduce**

1. Go to github repository
2. Make git cline
3. `pnpm i` - `pnpm dev`
5. go to /appointment route
6. choose date and click 'book appointment' button
7. choose 'telegram'
8. See no exit animation
9. If you click 'back' button you will see animation

**Comment by AppleFanBoy0941** [comment]
I have not cloned it but just looking at your code I maybe found some solutions

1. I can see you have an `<AnimatePresence>` inside your ternary. As far as I know, that won't do anything and maybe it would prevent the "real" `<AnimatePresence>` (the one just outside your ternary) from working
2. You haven't defined a key prop. React uses the key prop to differentiate different elements. Without the key prop it would not think the element has been changed. I would usually call divs like these ones for `key="buttons"` and `key="step-2"`. Because React treats these divs as different elements now, the animation should trigger.

I also noted that your `animate`-prop had `translateX: ['-100%', '0%']`. This is not necessary because you have already set `initial` to be -100%. Framer Motion will animate from initial to animate.
Also you can use `x` instead of `translateX`, x is used as a shorthand for `translateX`

**Comment by nicitaacom** [comment]
> 1.  About `<AnimatePresence>
I tried diffenet ways and I tried delete that `<AnimatePresence>`
![image](https://github.com/framer/motion/assets/39565703/9edb3f86-e3e9-4071-92f8-9eb6be8391eb)

2. I got this buggy effect
https://streamable.com/qjmwms

Updated code - https://github.com/nicitaacom/14_portfolio/blob/issue-framer-motion2/app/appointment/page.tsx

**Comment by AppleFanBoy0941** [comment]
Hmmm maybe try having both `initial`, `animate` and `exit` in your components.

It should look like this:
```
<motion.div
  initial={{ x: "-100%" }}
  animate={{ x: "0%" }}
  exit={{ x: "100%" }}
>
 ...
</motion.div>
```

I have experienced that keyframes on animate isn't working if it's the entering animation.
`initial` usually works for me

Also I just remembered that `<AnimatePresence>` needs `mode="popLayout"` prop
This ensures that the element's doesn't push each other away

**Comment by nicitaacom** [comment]
> Hmmm maybe try having both `initial`, `animate` and `exit` in your components.

Thank you - that work for me (I changed `mode="popLayout'` to `mode='wait')

https://streamable.com/m8uk8c

### Code that solved issue
```tsx
 <AnimatePresence mode="wait">
          {step === "initial" ? (
            <motion.div
              key="initial"
              initial={{ x: "-100%" }}
              animate={{ x: "0%" }}
              exit={{ x: "-125%" }}
              transition={{ duration: 0.25 }}
              className="flex flex-col gap-sm tablet:flex-col w-[80%] mx-auto">
              <Button onClick={() => setStep("telegram")}>
                Telegram call <PiTelegramLogoBold />
              </Button>
              <Button onClick={() => setStep("discord")}>
                Discord call <RiDiscordLine />
              </Button>
              <Button onClick={() => setStep("phone")}>
                Phone call <BsPhone />
              </Button>
            </motion.div>
          ) : (
            <motion.div
              key="communication-method"
              initial={{ x: "100%" }}
              animate={{ x: "0%" }}
              exit={{ x: "100%" }}
              transition={{ duration: 0.25 }}>
              <p>Hello step 2</p>
            </motion.div>
          )}
        </AnimatePresence>
```
