### ISSUE TITLE
[BUG] loop animation doesnt work 

### ISSUE THREAD

**Issue by issam-seghir** [framer/motion#2397]
**Describe the bug**
The setting icon should loop (rotate infinitly )  when using ` transition={{ repeat: Infinity, duration: 3}}` without any delay 
but there is a delay when the duration ends see the screenshot below : 
![screenshots](https://i.imgur.com/cCmEsn5.gif)

Despite using `repeatDelay:"0"`, the delay still persists !!
- [CodeSandbox ](https://codesandbox.io/p/sandbox/flamboyant-brook-q4jw9x)

**Expected behavior**

The setting icon rotate infinitely without any delay between repeat like a spinner 

**Environment details**
Windows 10 pro 22H2 (OS Build 19045.3570)

**Comment by juancarloscanoruiz** [comment]
Hey @issam-seghir! 

From what I understood your problem is you don't want the animation to slow down when it ends and also when it starts. I think this does not have to do with the delay, it is just how the animation works by default. To avoid this behavior you can just set the `ease` property to `linear` and I think with that the problem could be resolved

```

export default function App() {
  return (
	<Sheet variant="soft" >
		<Box  sx={{ backgroundColor:"neutral" ,display: "flex", height: " calc(100dvh - var(--variant-borderWidth) *2 )", alignItems: "center",justifyContent:"center" }}>
			<Tooltip title="setting" size="md" variant="solid" color="primary" placement="top" arrow>
				<IconButton component={motion.button} whileHover={{ scale: 1.1 }} whileTap={{ scale: 1 }} variant="solid" color="primary" size="lg" sx={{ zIndex: 2, borderRadius: "50%", p: ".5em"}} onClick={() => setShowSettings(!showSettings)}>
					<motion.div animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 5, ease: "linear" }}>
						<FiSettings />
					</motion.div>
				</IconButton>
			</Tooltip>
		</Box>
	</Sheet>
  );
}

```

Here's the docs related to the ease property: https://www.framer.com/motion/transition/

Here's  the same demo you sent but with the linear ease: https://codesandbox.io/p/sandbox/wandering-feather-3gmm9g

**Comment by issam-seghir** [comment]
oh thanks, It never occurred to me that the ease function is the case for this
