### ISSUE TITLE
React router v6 - mode = "popLayout"

### ISSUE THREAD

**Issue by christopherGr** [framer/motion#2407]
Hello,

I am trying to use framer-motion along with react router v6. 

```
<AnimatePresence mode="popLayout" initial={false} >	
	<Routes location={location} key={key}>
		{children}
	</Routes>
</AnimatePresence>
```	
The following warning occurs:
_Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
Check the render method of `PopChild`. at Routes_

The error occurs due to mode="popLayout". The docs declares that:
_Custom component note: When using popLayout mode, any immediate child of AnimatePresence that's a custom component must be wrapped in React's forwardRef function, forwarding the provided ref to the DOM node you wish to pop out of the layout._

Is there any way to pass the ref to Routes ??

**Comment by mattgperry** [comment]
Honestly I'm not actually sure. Is it possible to wrap it in a different component with `location` as the key? I'm marking as a `wontfix` as I'll not get round to any specific library integration.

**Comment by MrUltimate** [comment]
I'm getting the same error with NextJS

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```

**Comment by ryan-weisenberger** [comment]
So i had been struggling with this for a while, and I finally got it to work using two strategies. First, I used this article to get the outlets rendered correctly: https://medium.com/@antonio.falcescu/animating-react-pages-with-react-router-dom-outlet-and-framer-motion-animatepresence-bd5438b3433b

Second, I had to put the "motion.div" directly under the AnimatePresence, wrapping the cloned outlet, and I set a "key" on the motion.div equal to the location.pathname. That at least got the popLayout working correctly. I'm still having an issue with getting custom variant values to work, since the motion.div is only rendered once, but that's another story...
