### ISSUE TITLE
[BUG] useScroll doesn't work correctly in production build

### ISSUE THREAD

**Issue by guillegette** [framer/motion#2452]
I have a very simple component:

```
function TextItem({ children, className, elRef }) {
  const { scrollYProgress } = useScroll({
    // This makes it work in productin build
    // https://stackoverflow.com/questions/74797570/react-framer-motion-animation-works-in-development-but-doesnt-work-in-productio
    layoutEffect: false, 
    target: elRef,
    offset: ["start end", "end start"],
  });

  const opacity = useTransform(
    scrollYProgress,
    [0.3, 0.5, 0.5, 0.7],
    [0, 1, 1, 0]
  );

  return (
    <motion.div className="absolute w-4/5 -translate-y-1/2 top-1/2" style={{opacity, display: `${opacity === 0 ?? 'none'}`}}>
      {children}
    </motion.div>
  );
}
```

In dev it works just fine, but when creating a production build (next.js) the `scrollYProgress` will just be completely off. The only way I found to fix it was using `layoutEffect: false,` but I can't find anywhere in the docs what this actually does and why does it fix my issue? 

Thanks

**Comment by michael-harvey** [comment]
The discrepancy with dev vs prod might just be due to the double render nature of react, try disabling[ strict mode in next ](https://nextjs.org/docs/pages/api-reference/next-config-js/reactStrictMode). 

If that makes dev behave the same as prod, it's possible this is due to the hybrid nature of SSR/CSR of next.js, and useLayoutEffect is getting called too early when things aren't hydrated yet 🤔

**Comment by mattgperry** [comment]
Sorry without a reproduction I can't help further. `layoutEffect: false` changes the initial measurement to `useEffect` vs `useLayoutEffect`. Perhaps something is breaking the size of your page (ie `height: 100%`) only in production?
