### ISSUE TITLE
useRelative

### ISSUE THREAD

**Issue by steveruizok** [framer/motion#251]
The `useRelative` hook allows for complex transforms against _multiple_ values or motion values.

![ScreenFlow](https://user-images.githubusercontent.com/23072548/62044331-8999a900-b1fa-11e9-9263-5c398ad6a658.gif)

```tsx
const averageX = useRelative(
    (a, b, c) => (a + b + c) / 3, 
    xA,
    xB,
    xC
)
```

The hook works by taking a _computing_ function and one or more _related values_. These related values may be numbers, strings, or motion values. When any of the related values change, the hook will compute a new value for its motion value by running the current value of each of its related values through the computing function.

The computed values may be quite complex – and they may also include _other computed values_. However, the resulting code is nonetheless declarative, highly efficient, and fully juices the creative plane.

You can preview the `useRelative` hook on the [useRelative-useBetween branch](https://github.com/framer/motion/tree/useRelative-useBetween). (An earlier version of this branch also included a second hook, `useBetween`). 

## Limitations

At the moment, each related value passed to the hook must be either of the same type (e.g. all `number`s) or a mix of values and motion values of the same type (e.g. `number`s and `MotionValue<number>`s). This is not a hard constraint: the hook should be able to take any values and pass them into the callback accordingly; however, this may be beyond the limits of my TypeScript-Fu.

## Background

The `useTransform` hook is great for computing a motion value from the result of some other motion value.

```tsx
const shadowX= useTransform(xA, v => v - 4)
```

However, the library does not support computed values that are the result of several other values. For example, if I wanted a motion value that was between two other motion values, and which would update when _either_ of those values changed, the solution would be pretty tedious:

```tsx
const betweenX = useMotionValue(0)

const calc = React.useCallback((a, b) => {
   betweenX.set(a + (b - a) / 2)
}, [])

React.useEffect(() => {
  const cancelA = xA.onChange(v => calc(v, xB.get()))
  const cancelB = xB.onChange(v => calc(xA.get(), v))
  return () => {
    cancelA()
    cancelB()
  }
}, [])
```

This hook greatly simplifies this (common) part of complex interfaces/animations.

## Other options

This hook could possibly be merged into the `useTransform` hook.

```
// Simple
useTransform(xA, v => v - 4)

// Range interpolation
useTransform(xA, [0, 100], [32, 68])

// Relative
useTransform([xA, xB], (a, b) => (a + b)  / 2)
```

**Comment by InventingWithMonster** [comment]
Yeah this is great - I actually wanted to look into extending `useTransform` to do multiple values but I hadn't thought about stuff like this 🥳

I think my most prefered API would possibly be 

```
useTransform([xA, xB], ([a, b]) => (a + b)  / 2)

// Maybe later
useTransform({ x: xA, y: xY }, ({ x: a, y: b}) => (a + b)  / 2)
```

As I see it basically does accept a transform function. I'd like to consider how this would work with array syntax as well.

**Comment by steveruizok** [comment]
Makes sense to me! Array syntax sounds like 2D interpolation (ie [this kind of thing](https://www.npmjs.com/package/2d-bicubic-interpolate)) which could get interesting but feels different than the current array syntax for `useTransform`.

I could imagine using the proposed syntax with 2D arrays, though.

```tsx
const getDistance = ([x1, y1], [x2, y2]) => Math.hypot(x2-x1, y2-y1) 

const distance = useTransform([[xA, yA], [xB, yB]], getDistance)
```

**Comment by natew** [comment]
Glad I found this as I was about to open a similar ticket. We have an interesting use case that may help design this API, or perhaps it's already covered and I'm just not understanding the right way to do things in motion yet.

We're building a carousel with a 3d effect, in which you can zoom in or out of the carousel at any time. When zoomed out, it tilts things (rotateY) differently and moved them off to the side (x).

With react-spring we had a single spring that controlled all of this state (rotateY + x + scale). Since springs can take an object of values you can set multiple at once, and have a single source of truth.

With framer, it seems since a motionValue only represents a single point, you need something like this. But you end up with a lot "more" code for this case (a lot less for other cases).

Unless I'm missing something! I looked at animation, but we need control over how some of these properties transform differently (different transition types). I know I should provide better examples here, once I get a better bearing I'll extract one and see what I come up with.

**Comment by controversial** [comment]
Is an extension of `useTransform` to support multiple input `MotionValues` still something planned for the future of `framer-motion`?
