### ISSUE TITLE
useScroll exhibits jumping on page load (Nextjs)

### ISSUE THREAD

**Issue by tommhuth** [framer/motion#2573]
**2. Describe the bug**

This might just be me missing something obvious, but as I was trying to implement a basic parallax effect I stumbled onto something I'm not quite sure what to do with.

When using `useScroll` and `useTransform` to translate an element from a range like `300px` to `-300px`, I noticed that the initial value of the element is set to `300px` before being replaced after the initial page render. This creates a very noticeable jump when the page loads in (see Codesandbox). I would expect the value to be immediately updated with a `useLayoutEffect,` and the `layoutEffect` param seems to support this. This issue happens also when no scroll restoration is happening. 

Why this obvious jump? The parallax example in the docs does not have the same issue: I'm assuming since the  default value matches the min value and they are both `0`. I wasn't expecting a basic parallax to be tricky, but in retrospect i guess my previous parallaxing have been on elements below the fold, where this issue would not be apparent. 

Should I not expect stable/predictable layout with `useScroll`?

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
Notice how the red box jumps into place:  [(https://y8zdgj-3000.csb.app/](https://y8zdgj-3000.csb.app/)

**4. Steps to reproduce**

1. `useScroll` and `useTransform` to translate an element 
2. reload page
3. notice how the element jumps around before settling  

**5. Expected behavior**
No jumping around.

**7. Environment details**
Chrome, Mac Sonoma

**Comment by mattgperry** [comment]
The problem is layout effects run synchronously with the initial **client** render, but if a page has been SSR'd then the first client render happens after the page has already been painted.

In this example, `scrollProgress` is dependent on the intersection of the tracked element within the viewport, and this is only measured when JavaScript runs, which is after the page has been painted. When the `0` value doesn't match that of the SSR'd offset we see the jump.

There is no way around this with any JS library other than hiding the element until page load.

Something like.

```jsx
const opacity = useMotionValue(0.01) // Avoid pinging your lighthouse score

useEffect(() => {
  opacity.set(1)
}, [])

return <motion.div style={{ opacity }} />
``` 

Or


```jsx
<motion.div initial={{ opacity: 0.01 }} animate={{ opacity: 1, transition: { type: false }} />
``` 

Or if you can accept only supporting new browsers there's view-timeline

https://developer.mozilla.org/en-US/docs/Web/CSS/view-timeline
