### ISSUE TITLE
[BUG] `useScroll` values are stuttering on mobile browsers

### ISSUE THREAD

**Issue by piscopancer** [framer/motion#2680]
I know this bug exists and was reported a number of times already. I just want the maintainers to have their heads on this issue. I cannot figure out the nature of this bug but it only works on mobile.

I do not have a gif from my phone, so imagine the bamboo twitching up and down as i scroll the page, that's exactly what the bug is
![image](https://github.com/framer/motion/assets/109352196/f601a791-3f9b-4523-a4a1-7ef7ab8b7b06)

**Comment by mattgperry** [comment]
Dupe https://github.com/framer/motion/issues/2507

**Comment by nboliver-ventureweb** [comment]
@mattgperry I see this is now closed, but I am still experiencing stuttering with framer-motion@11.3.19
Was there a fix that was added to resolve the issue?

Reduced test case of the issue is here: https://codesandbox.io/p/sandbox/headless-moon-9dt5n8?file=%2Fsrc%2FApp.js
and you can view the bug on your phone here: https://9dt5n8.csb.app/
