### ISSUE TITLE
Subtle shifting of content while running layoutTransition

### ISSUE THREAD

**Issue by rijk** [framer/motion#274]
**Describe the bug**
Comment moved from #268. With longer content, the transform inversion isn't always exactly in sync with the parent (haven't managed to reproduce this in the Sandbox, but here's a screen recording):

![ezgif-1-3ccc9ad12e73](https://user-images.githubusercontent.com/159500/62712890-0a775280-b9fc-11e9-91fb-54534b04878b.gif)

**Desktop:**
 - OS: MacOS
 - Browser Chrome
 - Version 75

**Comment by InventingWithMonster** [comment]
Hi Rijk, I am going to need a Sandbox reproduction to be able to look into this one. I'm going to close it for now but please re-open if you get one.

**Comment by Rijk** [comment]
All right, finally managed to reproduce this one somewhat.

1. https://codesandbox.io/s/example-growing-container-with-layouttransition-9d5tl
2. Click Toggle
3. Quickly click Toggle again (before the expand transition is finished)
4. Observe the "3 replies" text bouncing a little — expected result: text absolutely fixed in position

Also:

1. Add some replies (e.g. 6)
2. Click Toggle to expand/collapse
3. Observe that end the end of the transition, both the "6 replies" text and the reply divs get a slight vertical nudge

**Comment by InventingWithMonster** [comment]
Thanks Rijk!

**Comment by InventingWithMonster** [comment]
Closing as `layoutTransition` has been removed.

**Comment by rijk** [comment]
Thanks for following up Matt. I've [updated the CodeSandbox](https://codesandbox.io/s/example-growing-container-with-layouttransition-forked-fu8gm) to see if the issue was gone, and this made me realise how much the API has improved. So first off really great work on that. Also the performance is rock solid, the `layout` scale + position inversion is working really well now. Hats off to you man!
