### ISSUE TITLE
Documentation wrongly suggests using motion.create for custom components

### ISSUE THREAD

**Issue by vincentreynaud** [framer/motion#2796]
The [current Framer documentation](https://www.framer.com/motion/component/#custom-components) suggests to create custom components in the following way:

```
const Component = React.forwardRef((props, ref) => (
    <div ref={ref} />
))

const MotionComponent = motion.create(Component);
```

when in fact one should use this, at least for the latest packages. 
```
const MotionComponent = motion(Component);
```

Took me a bit to find out after encountering a few stack overflow issues. 

Please fix the docs of an otherwise amazing library 🙏

**Comment by mattgperry** [comment]
Did you try `motion.create` and it wasn't working?

**Comment by vincentreynaud** [comment]
Ok so I believe it was throwing an error in my gatsby app previously. Lost track of what changed but i managed to make both work now. Sorry for the false alert.

**Comment by manuelpoelzl** [comment]
Just updated my modules and saw that the `motion`  function no longer works, same goes for `motion.create`
![image](https://github.com/user-attachments/assets/e979bec9-bec1-49b8-a9df-f38ed1a686ff)

But this way I can not use the library anymore with 3rd party UI components, since I can not control how these components are structured. 
Seems like the only way to use framer with 3rd party UI components is to create a new component, which then renders the UI component from the framework right?
