### ISSUE TITLE
[BUG] Compile error: `Type 'undefined' is not assignable to type '(animation: AnimationPlaybackControls) => VoidFunction'.`

### ISSUE THREAD

**Issue by fxnm** [framer/motion#2861]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

When trying to build a project that uses framer-motion and `"skipLibCheck": false` the build fails. 
If version is greater or equals to `v11.9.0`

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/p/devbox/jolly-mountain-66wd57

**4. Steps to reproduce**

1. Create a react 18 project with vite, typescript and framer-motion
2. Make sure that `skipLibCheck` is set to `false`
3. Add a component to the app, so the lib gets compiled
4. Run `npm run build`

**5. Expected behavior**

The Application should build without errors.
But i got instead the following **INTERNAL** type error:

```
node_modules/.pnpm/framer-motion@11.11.11_react-dom@18.2.0_react@18.2.0/node_modules/framer-motion/dist/index.d.ts:3824:5 - error TS2416: Property 'attachTimeline' in type 'GroupPlaybackControls' is not assignable to the same property in base type 'AnimationPlaybackControls'.
  Type '(timeline: any, fallback: (animation: AnimationPlaybackControls) => VoidFunction) => () => void' is not assignable to type '(timeline: ProgressTimeline, fallback?: ((animation: AnimationPlaybackControls) => VoidFunction) | undefined) => VoidFunction'.
    Types of parameters 'fallback' and 'fallback' are incompatible.
      Type '((animation: AnimationPlaybackControls) => VoidFunction) | undefined' is not assignable to type '(animation: AnimationPlaybackControls) => VoidFunction'.
        Type 'undefined' is not assignable to type '(animation: AnimationPlaybackControls) => VoidFunction'.

3824     attachTimeline(timeline: any, fallback: (animation: AnimationPlaybackControls) => VoidFunction): () => void;
         ~~~~~~~~~~~~~~


Found 1 error in node_modules/.pnpm/framer-motion@11.11.11_react-dom@18.2.0_react@18.2.0/node_modules/framer-motion/dist/index.d.ts:3824
```

**7. Environment details**

Build fails on linux/windows using npm/pnpm/yarn

**Comment by spaceC00kie** [comment]
I'm dealing with this bug too.

**Comment by mattgperry** [comment]
It's quite tough to fix this given Motion could have been built with different settings than the consuming code base. Is there a reason for disabling `skipLibCheck`? And how do you deal with other libraries, do they just tend to work?

**Comment by geektechniquestudios** [comment]
> It's quite tough to fix this given Motion could have been built with different settings than the consuming code base. Is there a reason for disabling `skipLibCheck`? And how do you deal with other libraries, do they just tend to work?

I'm not the OP, but the main reason I use "skiplibcheck: false" is primarily because new Vite apps start out configured this way, and because disabling it could hide bugs. I refer to [this stack overflow question](https://stackoverflow.com/questions/52311779/usage-of-the-typescript-compiler-argument-skiplibcheck) when deciding whether to enable the setting. 

I have a massive multimillion line app using framer motion (which I love, thanks for this tool ❤️). It is the only dependency causing a build error, and yes, other libraries just work. My current hack solution is to manually modify the node module dist index file with the change that @fxnm  has proposed, but my build pipeline doesn't work smoothly without skipping the lib check. 

I hope the tiny fix can get merged into the main codebase soon. Thanks for everything.

**Comment by billyjanitsch** [comment]
>Is there a reason for disabling skipLibCheck? And how do you deal with other libraries, do they just tend to work?

>it feels very much to me like writing tests against external libraries

@mattgperry I understand this perspective, but consider that this flag isn't telling TypeScript to check the _source_ of libraries, just the compiled and published `.d.ts` typings which are "flattened" to only include consumer-facing exports.

One reason not to enable the flag is that when it's disabled, if TypeScript can't determine a type because of an issue in a dependency's type defs, it silently converts that type to `any`. This makes it easy for `any`s to sneak into an application codebase, especially when upgrading dependencies.

I can definitely understand why some enable the flag, but I hope this helps explain why it's off by default and why you might choose to leave it off. Re your other question, other libraries do tend to work with the flag off. This issue is the first I've seen across our codebases' dependencies in a few years.
