### ISSUE TITLE
[BUG] `exit` doesn't work when triggered from `onDragEnd`

### ISSUE THREAD

**Issue by lintonye** [framer/motion#293]
**Describe the bug**
`exit` animation doesn’t play if triggered from `onDragEnd`

**To Reproduce**
1. Go to 'https://codesandbox.io/s/task-list-3684r'
2. Drag any item to the right

**Expected behavior**
The item should fade out since there's an `exit` prop set on the div that animates its opacity.

Clicking the "remove" button, you'll see the expected animation.

**Screenshots**
video: https://framer-team.slack.com/archives/G5VQ146US/p1563386007188000

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4
 - Browser: Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by InventingWithMonster** [comment]
Thanks for the bug report Linton, very clear example. I'll take a look at this one next.

**Comment by InventingWithMonster** [comment]
What's happening here is `AnimatePresence` adds an `onAnimationComplete` to know when the exit animation has completed.

However, the way `exit` works is by internally overwriting the `animate` prop, and the way `onAnimationComplete` works is by firing when *any* animation completes.

In the included example, if you throw hard enough the exit animation behaves as expected. But if dragging ends without momentum, the drag end animation completes immediately, triggering `onAnimationComplete` before the exit animation has completed.

On solution may be to change `applyExitProps` to `useExitProps` or similar, and have that accept the component's `ValueAnimationControls`. Instead of overwriting `exit` with `animate`, we'd use a `useEffect` to fire the `exit` animation using the `ValueAnimationControls` directly rather than "tricking" the associated animation handler to run its normal comparison algo. This would also fix https://github.com/framer/motion/issues/276

**Comment by InventingWithMonster** [comment]
This will be fixed in `1.6.8` next week
