### ISSUE TITLE
[QUESTION] How to Delay Children Animations with AnimatePresence  

### ISSUE THREAD

**Issue by ryanwiemer** [framer/motion#294]
**Describe the bug**
I am using `AnimatePresence` on a simple example to fade in pages as they are mounted/unmounted. This works as expected. What I am struggling with is delaying the individual children animations on each page to wait until after the fade has completed first. 

Using Pose and the `PoseGroup` I accomplished this with code similar to this: 

```
const Transition = posed.div({
  enter: {
    opacity: 1,
    transition: { duration: 300 },
    delay: 300,
    beforeChildren: true
  },
  exit: { opacity: 0, transition: { duration: 300 } }
});
```

With Framer Motion and `AnimatePresence` my code looks similar to this : 
```
const variants = {
  initial: {
    opacity: 0,
  },
  enter: {
    opacity: 1,
    transition: {
      duration: .3,
      delay: .3,
      when: 'beforeChildren',
    },
  },
  exit: {
    opacity: 0,
    transition: { duration: .3 },
  },
}
```

**To Reproduce**
**Code Sandbox** - https://codesandbox.io/s/github/ryanwiemer/gatsby-using-page-transitions
**Github Repo** - https://github.com/ryanwiemer/gatsby-using-page-transitions/blob/master/src/components/Layout.js

1. Go to https://transitions.netlify.com/
2. Navigate between the pages to see the basic page fade.
3. Navigate to the "Animated" page. The list of items should do a stagger fade in but that animation occurs at the same time as the page fade so you don't see it. 

**Expected behavior**
I expect the top level page fade to occur followed by the children animations. Right now all animations are occurring at the same time.

**Comment by ryanwiemer** [comment]
@InventingWithMonster 

Is this intentional behavior on `AnimatePresence`? Or should this be categorized as a bug?

**Comment by msheakoski** [comment]
I was incorrect before about initial -> animate not working. In my CodeSandbox, it correctly staggers the initial children, even with AnimatePresence wrapping them. The problem occurs when actually swapping children, they all disappear/appear at the same time:

[![Edit peaceful-lovelace-l3o64](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/peaceful-lovelace-l3o64?fontsize=14)

**Comment by msheakoski** [comment]
I think the issue is that there is a disconnect between AnimatePresence and the parent Motion component where staggerChildren/delayChildren/when is defined.

In a structure like this:

```jsx
<motion.div key="parent" variants={variantsWithOrchestration}>
  <AnimatePresence>
    <motion.div key="child1" variants={childVariants} animate="visible" exit="hidden"/>
    <motion.div key="child2" variants={childVariants} animate="visible" exit="hidden"/>
    <motion.div key="child3" variants={childVariants} animate="visible" exit="hidden"/>
```

the animate prop on children cancels out any orchestration defined in the parent. My guess is that AnimatePresence needs to accept a variants prop directly, or inherit them from the parent, so it understands how to orchestrate the children.

**Comment by marozzocom** [comment]
Since AnimatePresence does not control the existence of its children, it is difficult to see how this should be implemented. What you can do is use AnimationPresence and control the visibility of your elements by yourself, delaying the rendering of components with a wrapping element, something like this:

https://codesandbox.io/s/framer-motion-animate-presence-stagger-children-7j0v3

Adding more items dynamically will need a bit more work, but this should give something to start with.

In my opinion this is not really bug but perhaps something that could be documented better. I spent a fair amount of time figuring out how to implement this.

**Comment by msheakoski** [comment]
@marozzocom It has been a long time since I last did something related to this, but from what I remember, I believe I did a similar implementation to yours but the problem is that I could stagger the "enter" animations of child components by manually increasing a shared delay, but I could not stagger the "exit" animations because there was no ability at the time to pass that delay to exiting components.

**Comment by rmacy** [comment]
This is an issue I'm running into. My use-case is a sidebar that expands out and needs to delay the rendering of its children until it's full expanded.

**Comment by kaankilic** [comment]
> This is an issue I'm running into. My use-case is a sidebar that expands out and needs to delay the rendering of its children until it's full expanded.

+1 for me. I am trying to animate menu items of sidebar with staggerChildren prop. However, it doesn't work for me

**Comment by thebetternewt** [comment]
I've been battling with this issue too. I found that if you make your child variant keys **exactly the same names** as your parent variant keys (in my case "enter" and "exit"), then it works!

Do not add "initial", "animate", or "exit" props on the child components -- only the relevant "variants" prop, like so:

```
import React from 'react';
import styled from 'styled-components';
import { motion, Variants } from 'framer-motion';

const containerVariants: Variants = {
  enter: {
    x: 0,
    opacity: 1,
    transition: {
      when: 'beforeChildren',
      staggerChildren: 0.4,
    },
  },
  exit: { x: -300, opacity: 0 },
};

const childVariants: Variants = {
  enter: {
    x: 0,
    opacity: 1,
  },
  exit: {
    x: -20,
    opacity: 0,
  },
};

const childVariants2: Variants = {
   enter: {
    x: 0,
    opacity: 1,
    color: 'red',
  },
  exit: {
    x: -20,
    opacity: 0,
    color: '#000',
  },
};

export const Menu = () => {
  return (
    <MenuWrapper
      variants={containerVariants}
      initial="exit"
      animate="enter"
      exit="exit"
    >
      <motion.h2 key="heading" variants={childVariants}>
        My Menu
      </motion.h2>

      <motion.h3 key="subheading" variants={childVariants}>
        Section 1
      </motion.h3>

      <motion.h3 key="subheading" variants={childVariants2}>
        Section 2
      </motion.h3>
    </MenuWrapper>
  );
};

const MenuWrapper = styled(motion.div)`
  position: absolute;
  top: 0;
  bottom: 0;
  width: 300px;
  padding: 20px 1rem;
  background-color: #111;
  color: #fff;
  box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06);
  z-index: 8;

  h2 {
    margin: 0 0 1rem;
  }
`;
```

Note that I'm rendering this component inside of a `<AnimatePresence>` component with React Router Dom:

```
import React from 'react';
import { Route, Switch, useLocation, BrowserRouter } from 'react-router-dom';

import { AnimatePresence, motion } from 'framer-motion';
import { Menu } from './components/layout/Menu';

function App() {
  const location = useLocation();

  return (
      <AnimatePresence exitBeforeEnter>
        <Switch location={location} key={location.pathname}>
          <Route exact path="/">
            <Menu />
          </Route>
        </Switch>
      </AnimatePresence>
  );

export default () => (
  <BrowserRouter>
    <App />
  </BrowserRouter>
);

**Comment by em** [comment]
If I understand correctly, it seems like the root problem here is that the orchestration is queuing transitions based on variant names, rather than the transitions themselves. Is there a plan to change this behavior so that dependent animations will queue regardless of the names in the future?

**Comment by em** [comment]
For the record, the solution thebetternewt posted won't help if you're using AnimateSharedLayout. Doesn't seem there is any way to delay the exit transition for a layout element inside AnimateSharedLayout.

@InventingWithMonster Is there any workaround for this?

**Comment by danielo515** [comment]
> I think the issue is that there is a disconnect between AnimatePresence and the parent Motion component where staggerChildren/delayChildren/when is defined.

The situation explained by @msheakoski is the key part on all this. If you have the transitions orchestrated by a parent component, but you have the animate presence in between that orchestration is lost. In my case I can see how this happens because I have one child that is outside the animate presence and on that child the delays are being applied correctly.
It will be awesome if this can be fixed so we don't have to handle the delay with an animation function

**Comment by danielo515** [comment]
As you can see here on the component hierarchy the context provider in the middle has the initial value as undefined.

![image](https://user-images.githubusercontent.com/2270425/113501106-56590280-9523-11eb-93b7-f17a69a4c5b2.png)

If anyone needs to visualise how this component looks like, it is like this 
![image](https://user-images.githubusercontent.com/2270425/113501135-843e4700-9523-11eb-8e83-bf581f1dd04b.png)

**Comment by danielo515** [comment]
Ok, I found where my problem was (bless a good sleep night).

This was the code of my component (a bit simplified):

```js
    <motion.div
      variants={menuVariants}
      className={css.menuRoot}
      animate={isOpen ? "open" : "closed"}
      layout
    >
      <IconButton
        component={motion.button}
        variants={crossVariants}
        onClick={close}
      >
        <Add />
      </IconButton>
      <AnimatePresence>
        {[
          { icon: <Settings />, path: "/settings" },
          { icon: <AccountCircle />, path: "/profile" },
          { icon: <PlaylistAdd />, path: "/new-name" },
        ].map(
          ({ icon, path }, idx) =>
            isOpen && (
              <motion.div key={path} variants={itemVariants} custom={idx}>
                <Link to={path}>
                  {icon}
                </Link>
              </motion.div>
            )
        )}
      </AnimatePresence>
    </motion.div>
```

As I mentioned on my previous comment, the context provider in the middle was missing the initial property, and that clicked on my mind. Not having an initial property on the parent motion component was the root cause of the problem. It is ok for the parent component because it will toggle between animate and close when you switch the animate property, but the children are missing a proper initial property to animate from.

The solution was a simple as this:

```
    <motion.div
      variants={menuVariants}
      className={css.menuRoot}
      initial="closed"
      animate={isOpen ? "open" : "closed"}
      layout
    >
```

Hope this helps someone figure their problem because the feature seems to work properly on framer-motion 4.1.2

**Comment by NayamAmarshe** [comment]
> I've been battling with this issue too. I found that if you make your child variant keys **exactly the same names** as your parent variant keys (in my case "enter" and "exit"), then it works!
> 
> Do not add "initial", "animate", or "exit" props on the child components -- only the relevant "variants" prop, like so:

Thanks for this! It seems that adding initial, animate on children overrides the stagger effect. This took me so long to fix!

**Comment by weiyolan** [comment]
I'm properly making use of `variants` props and `whenInView` to orchestrating the sequential fade-in of a parent and its children. 
As stated in the documentation when declaring new animations on children their staggered behaviour cancels. 
It seems that when using the `whenFocus`, `whenHover`, `whenTap` props, the children are still staggered but they do not come back to their initial state. I believe since the `initial` variant declares invisible states when used in combination with `whenInView`. 

Here's the Parent:

`<motion.div initial='hidden' whileInView='visible' variants={parentVariant} viewport={{once:false}} className='w-full mt-20 grid grid-cols-6 gap-4 grid-flow-row relative'>
        {logos.map((logo,i)=>{
          return <Logo key={i} color={logo.color} white={logo.white}/>
        })}
</motion.div>`

With variants:

```
let parentVariant = {
  visible: {
    opacity:1,
    transition: {
      when: 'beforeChildren',
      staggerChildren: 0.05,
    }
  },
  hidden: {
    opacity:0,
    transition: {
      when: 'afterChildren',
    }}
 }
```

And inside the _Logo_ children: 

`let logoVariant={
    visible: {
        y:0,
        opacity: 1,
        scale: 1,
        transition:{type:'spring', bounce: 0.4, duration:0.8},
    },
    hidden: {
        y: 30,
        opacity: 0,
        scale:1
    },   
}

return (
    <motion.div variants={logoVariant} className='relative flex max-h-20 p-2 hover:scale-105' onClick={()=>setClick(oldState=>!oldState)}>
        {white}
        {/* {click?color:''} */}
        {/* <div className={`relative mx-auto w-full inline-block h-auto z-10`}>{}</div> */}
    </motion.div>
)`

**Comment by weiyolan** [comment]
It turns out that the children are scaled back to a normal stated when the initial scaling factor is announced in the parent variant only. That's weird! These are the variants that make it work:

```
let logoVariant={
    visible: {
        y:0,
        opacity: 1,
        // scale:1, No scale here
        transition:{type:'spring', bounce: 0.4, duration:0.8},
    },
    hidden: {
        y: 30,
        // scale:1, No scale here
        opacity: 0,
    },   
}

 let variant = {
  visible: {
    opacity:1,
    scale:1, //Only in parent variant
    transition: {
      when: 'beforeChildren',
      staggerChildren: 0.05,
    }
  },
  hidden: {
    opacity:0,
    scale:1, //Only in parent variant
    transition: {
      when: 'afterChildren',
    }}
 }
```
