### ISSUE TITLE
[BUG] AnimatePresence & staggerChildren doesn't work when only some children are leaving and entering at the same time.

### ISSUE THREAD

**Issue by agonsalves** [framer/motion#305]
**1. Describe the bug**
When you have AnimatePresence wrapped around a motion.div that has the staggerChildren transition, the initial rendering of the entire block works. However, if you remove some of the children, they do not use their exit animation. Then, when you add them back, they all come back at once.

**2. Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/embed/wonderful-dubinsky-75s3n

**3. Steps to reproduce**
Just use the toggle in the code sandbox

**4. Expected behavior**
I expect the exit animation to happen when the items unmount. I also expect that when the items are mounted again, they are staggered.

**Comment by msheakoski** [comment]
This was also brought up in #294. Linking here because you have a good Code Sandbox example.

**Comment by mattgperry** [comment]
`AnimatePresence` isn't going to work in this instance because its root child never leaves. This isn't a bug but improper use of the API.

When the children enter again, the parent isn't animating, so it can't stagger its children. This is a trickier one to solve and I don't see a fix on the horizon that would work as expected in all situations, I would recommend using a custom `delay` strategy here.
