### ISSUE TITLE
[BUG] [iOS13] whileTap doesn't animate back to initial props when interrupted with scrolling

### ISSUE THREAD

**Issue by gusso** [framer/motion#310]
## Description
`whileTap` should animate back to initial element props when tap is over, but that doesn't happen when starting a scroll from the tap target.

## Environment
• iOS 13.1 beta (17A5821e) (also on iOS 13.0 builds)
• Safari

## Demo
https://codesandbox.io/s/runtime-night-f0o8i
![Kapture 2019-09-01 at 7 19 04](https://user-images.githubusercontent.com/782754/64072567-ed474400-cc88-11e9-858f-4bda6d9bc5a8.gif)

**Comment by gusso** [comment]
Seems connected to https://github.com/framer/motion/issues/281, adding `touch-action: none` to the tap target stops the scrolling from happening and enforces the tap always finishes.

**Comment by FuchsbergerTbs** [comment]
Is this a problem related to framer motion or is it a temporary bug in safari on iOS 13? On iOS 12 it works like a charm.
I'm asking because the `touch-action: none` solution doesn't cut it for me because I want to build a table-like layout where every cell is clickable, needless to say that `touch-action: none` doesn't work here because scrolling wouldn't work anymore.

**Comment by GitIgnoreMaybe** [comment]
It doesn't work on Android either. Generally it would be great if those events e.g. whileTap are not triggered in the first place if ontouchmove is true.

**Comment by IljaDaderko** [comment]
Happens on chrome (macOS) as well, setting `touch-action` to anything that is "pan" for an element that has `whileTap` seems to trigger this behaviour.

**Comment by IljaDaderko** [comment]
Elements that have `whileTap` fire `onPointerDown` event, but after scrolling and releasing a finger they don't fire `onPointerUp` event, only when you click somewhere on the screen again.

**Comment by IljaDaderko** [comment]
Something like this works as a workaround, but it is very involved i.e. you would need to dispatch "scrollEnded" event from your scrollable view to let all your components they need to animate back to normal position, ideally we still want `onPointerUp` event to fire:

```tsx
function Card({ onTap, children }: Props) {
  const animation = useAnimation();

  useSubscribe('scrollEnded', () => {
    animation.start({ scale: 1 });
  });

  return (
    <motion.div
      onPointerDown={() => {
        animation.start({ scale: 0.95 });
      }}
      onPointerUp={() => {
        animation.start({ scale: 1 });
      }}
      onTap={onTap}
      animate={animation}
    >
      {children}
    </motion.div>
  );
}
```

**Comment by IljaDaderko** [comment]
Not sure if this is what's causing the issue, but when I start scrolling `onPointerCancel` event is fired, and because of this `onPointerUp` never gets called. Looking at the source of whileTap https://github.com/framer/motion/blob/44f36a31c02bf63eaf3b34153326fa44a0ff712c/src/gestures/use-tap-gesture.ts

I don't see anything related to this cancel event, perhaps it should trigger same actions as `onpointerUp` ?

**Comment by Ventricci** [comment]
Did anyone find a solution to this issue? I'm having same problem when scrolling a listView with Clickable cards.
