### ISSUE TITLE
[BUG] AnimatePresence with motion.div containing a ref blows up

### ISSUE THREAD

**Issue by mattcolman** [framer/motion#341]
**2. Describe the bug**
When a child of AnimatePresence contains a ref there is a bug that occurs.
"Uncaught Error: No valid node provided. Node must be HTMLElement, SVGElement or window."

**3. Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/framer-motion-animate-presence-6ksyh

**4. Steps to reproduce**
1. Click 'add new' TWICE
2. Click clear
3. Notice the error
4. *Note* if you remove the ref from the codesandbox example it works fine.

**5. Expected behavior**
There should be no error

**7. Environment details**
MacOS latest Chrome

Thanks!!

**Comment by amannn** [comment]
I'm wondering if this is related to https://github.com/framer/motion/pull/335. The error seems to be the same, not sure if the cause is related.

**Comment by InventingWithMonster** [comment]
This is an interesting one - I'm going to look into it further but I suspect it has something to do with the fact that although we're rendering "one" component at a time we're actually rendering multiple components until the exiting ones animate out. By providing `ref`, rather than allowing them to all hold an internal ref to their own element we're forcing them to share one. Which could be leading to a host of unexpected behaviours. I hope to resolve this but it *might* be impossible.

**Comment by InventingWithMonster** [comment]
Fixed in `1.6.10`. @amannn could you try this version for your other issue, if it's not fixed I'll take a deeper look.

**Comment by amannn** [comment]
@InventingWithMonster I've synced my fork where [the failing PR is open](https://github.com/framer/motion/pull/335) with the latest master, but it seems like there's still the same error.
