### ISSUE TITLE
[QUESTION] Collect motion element dimensions

### ISSUE THREAD

**Issue by souporserious** [framer/motion#360]
Hello 👋

I'm working on a button to input animation ([codesandbox](https://codesandbox.io/s/framer-motion-button-input-yj0si)) and I need to measure motion elements when the component mounts using `useLayoutEffect` to prevent flashing and animating on load. For some reason, `ref.current` is not available when the hook fires. I'm assuming because `motion` needs to know about it? Is there any way to grab the dimensions before the first paint? I appreciate any help 🙏.

**Comment by InventingWithMonster** [comment]
Hey man

Sorry for the delay in response - we've been heads-down on a different project.

This is because of the unique way the `motion` component dynamically loads in functionality components. I'm going to look into this a little bit now and see if there's a way we can re-order some stuff to make this available earlier.

**Comment by InventingWithMonster** [comment]
Ah it's because we load external refs manually in a useEffect: https://github.com/framer/motion/blob/master/src/motion/utils/use-external-ref.ts#L13

I'll have to look into why this change was made because there was a bug this fixed. Obviously we can't move this to useLayoutEffect because React will kick off during SSR.

**Comment by InventingWithMonster** [comment]
I think the "fix" here might have to be to revert the change made in `1.16.10` and add a warning in components that are children of `AnimatePresence` that a unique ref must be given to each unique child. This can be solved by making the child a separate component that has its own call to `useRef`

There's no real other solution here as far as I can tell.

CC @mattcolman

**Comment by souporserious** [comment]
Sounds good, Matt! I appreciate you looking into this, thank you! 🙏

**Comment by souporserious** [comment]
Not to get off-topic, but maybe a first-class way to access dimensions could help? I know you need to do measurements in certain use-cases like FLIP, it might be nice to expose a hook to read dimensions at the same time framer does to save from having to read from the DOM twice.

**Comment by InventingWithMonster** [comment]
That is a fantastic idea
