### ISSUE TITLE
[BUG] Drag doubles distance when provided an external MotionValue

### ISSUE THREAD

**Issue by satvikpendem** [framer/motion#416]
**Describe the bug**

I wanted to replicate this tutorial (https://www.youtube.com/watch?v=UMGnYRJuJog) that shows how to create a drag handle in Framer X. Using `framer-motion`, I thought it worked but I am getting extra space on dragging that shouldn't occur. It may be something with `display: flex` but I'm not entirely sure.

**IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[![Edit cool-newton-f2l3e](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wizardly-hypatia-20iue)

**Steps to reproduce**

Create two panels and a drag handle, and make the handle add width to one panel and subtract from another.

**Expected behavior**

The handle should drag and not have extra space. It should also follow the mouse which it is not doing.

**Video or screenshots**

![](https://imgur.com/J2fUUWh.gif)

**Environment details**

Windows 10, Chrome

**Comment by InventingWithMonster** [comment]
This is bizarre, it only seems to happen when provided an external motion value

**Comment by InventingWithMonster** [comment]
Ah I see. This is working correctly. It only happens in this example when provided an external motion value because you're adjusting the surrounding DOM layout at the same time.

Dragging is applied to the x/y transform. That white space is where the grey element **actually** is. Then a transform is applied on top of this.

The way to fix this is to position the grey bar absolutely where it currently appears. That way its position will remain unaffected by the other two elements and will reposition correctly as a result of the drag.

**Comment by satvikpendem** [comment]
Thanks for the advice @mattgperry. Would you be able to give a CodeSandbox link of the solution you're talking about? I'm not sure I exactly understand it.
