### ISSUE TITLE
Orchestration and Flip Transitions

### ISSUE THREAD

**Issue by carlosagsmendes** [framer/motion#417]
Hi there, I’m trying to create a FLIP animation using the layoutTransition. Here’s my code example: https://codesandbox.io/s/framer-motion-accordion-simple-yldde

**# Orchestration**

I’m trying to orchestrate the animation of the contents of the expanded element, using staggerChildren and delayChildren, as I only want to show the form fields after the element is expanded. 

But the content is appearing as soon as I expand the element:    

![Stagger](https://user-images.githubusercontent.com/1224078/71109567-5eb9ec80-21bd-11ea-8c74-b58768b5ceb8.png)

**# Flip with useInvertedScale**

My understanding from the docs is that I need to use useInvertedScale “for undoing the distortion of content when scaling a parent component“.

As you can see in this example https://codesandbox.io/s/framer-motion-accordion-simple-yldde, useInvertedScale works fine when expanding an element to fullscreen and using originY: 0, originX: 0.

But on close, the title gets displaced before animating back: 

![Expand](https://user-images.githubusercontent.com/1224078/71109588-6b3e4500-21bd-11ea-85b1-e68f0af6055f.png)

Can someone help me figure out what am I missing in both cases? 

Thanks in advance

**Comment by InventingWithMonster** [comment]
With the title you probably need to ensure both titles are anchored to the top left position perhaps using position: 'absolute', top: 0, left: 0 and applying your required padding to the element itself so it stays in the same position between states.

The fields not animating in when you expect is odd, it seems as if adding them to the tree is causing staggering not to work. It might be seeing "fullscreen" as its initial or current state rather than understanding its going from one to the other.

**Comment by mattgperry** [comment]
Just closing this as `layoutTransition` is deprecated in favour of `layout`. But feel free to reopen with an example based on `layout`, sorry I couldn't fix your problem here.
