### ISSUE TITLE
[FEATURE] Set initial variant/target object when using Animation Controls

### ISSUE THREAD

**Issue by dminkovsky** [framer/motion#437]
**Is your feature request related to a problem? Please describe.**

When using regular target objects or variants with the `animate` attribute and setting `initial={false}`, it is easy to set initial style.

However, when using Animation Controls, there doesn't seem to be a way to set initial state.

**Describe the solution you'd like**

The ability to set an initial target object or variant using Animation Controls.

**Describe alternatives you've considered**

Initial styles can be set with other mechanisms, but then they must be overridden properly by the animation variants. It would be nice if you could just specify an initial variant.

**Comment by InventingWithMonster** [comment]
The issue is that `AnimationControls` are inherently stateless, they're used to issue commands to controlled components. `initial` can accept maps of values as well, `false` just copies them from `animate`. So in this case they'd have to be set explicitly, as `AnimationControls` don't have any to copy.

**Comment by dminkovsky** [comment]
Wow yes, no sure what happened here. Sorry for this “brain fart” of an issue. I knew and even use `initial={target}` throughout my code. Thanks.
