### ISSUE TITLE
[FEATURE] Shared Element Transitions

### ISSUE THREAD

**Issue by rihok** [framer/motion#438]
One common pattern seen in both iOS and Android is [Shared Element Transitions](https://developer.android.com/training/transitions/start-activity). Meaning that you can have an element transform from one state or place, into another. A good example of this is when you open an app in iOS, where you see the app icon transform into the app. That particular example is already possible with framer motion, but what is not possible is having that element change it's position in your app hierarchy. A good example is the video in the Android example I linked to above.

There's a [react-morph](https://github.com/brunnolou/react-morph), that does a similar thing. I think this feature would make for a great addition to framer-motion.

In terms of API, I'm not familiar enough with hooks still to give a good example on that front, but I could certainly see it working pretty well with the already existing exit prop and some kind of additional ID on the motion element that would detect when a motion element with the same ID has moved to another place in the app and transition the changes between those states.

**Comment by InventingWithMonster** [comment]
Yeah I would love to do this. I wouldn't expect anything in the next few months though. I will be looking at a related area for an upcoming Framer feature but I don't know to what extent it will require new features in Framer Motion. But it is on my personal radar for sure and I agree with you that it shouldn't require much more than an ID prop and a `AnimatePresence`-style wrapping component.

**Comment by jakeleboeuf** [comment]
Any update on the progress of this feature? It looks like using `<AnimateSharedLayout />` handles this use case perfectly in Chrome, but Mobile Safari/Chrome (WKWebView) have some issues. I don't want to spin my wheels too long attempting to address this issue if there is a known solution?

### A few loom previews from very simple test I spun up in Gatsby:

✅ [Chrome](https://www.loom.com/share/da20b84d168c433eaabbed35aedd5b23)    |    ❌  [Mobile Safari](https://www.loom.com/share/f3568c30b2694d49bce671128770e3f5)    |    ⚠️ [Mobile Safari with an animated window.scrollTo([0, 0]) hack](https://www.loom.com/share/0b554ce4b6cd4363bd5ea44960698aee)

**Comment by jakeleboeuf** [comment]
Updating my comment here after spending some more time debugging this week- the problem seems to be with the window/document height, not necessarily the device (Although I'm not 100% that's not also a factor). I ported the App Store [Codesandbox demo over to a Gatsby sandbox](https://codesandbox.io/s/app-store-with-framer-motion-and-gatsby-lykm5) and swapped the modal for a true page transition to do some debugging.

## Discovery:
I think it's pretty reasonable to expect new screens will mount with a scroll position at the top of the document (`window.scrollTo(0, 0)`). So if that is the case, and if the `next page`'s `document height` is `<` the `window height`, everything works magically. However, if the `next page`'s `document height` is `>` the `window height`, the document will jump to the top of the window and we lose the magic of the transition. [Here it is in slow motion](https://www.loom.com/share/e122aeedfc1c4d86985cbb29b979890e). _Ignore all the other weird bugs, I'm just focusing on the movement of the cards here._ 

> I'm tempted to render an empty page on mount to force a short page height, exploiting the browser's magical behavior scrollTop behavior, and then update the DOM with content after the transition starts... but that's a bad idea.

I suppose I should actually look at the code to come to some useful conclusions, but I've run out of time to spend on this for the week and just wanted to share my findings if it's helpful!

**Comment by rihok** [comment]
Seems like the feature itself is now implemented, so it makes sense to be close this. I'd say bugs to do with the feature probably should be opened separately. Feel free to reopen this if you feel necessary though. @InventingWithMonster @jakeleboeuf

**Comment by tettoffensive** [comment]
@rihok Can you point me to a simple example? I've tried both `framer-motion` and `react-morph` and haven't got it to work. I just want to crossfade between two elements:

```ts
<small tw="text-gray-500 flex">
        {!dirty ? (
          <div tw="flex">
            <CheckmarkIcon tw="fill-current" />
            <span>Saved</span>
          </div>
        ) : (
          <div tw="flex">
            <EditIcon tw="fill-current" />
            <span>Saving…</span>
          </div>
        )}
</small>
```
