### ISSUE TITLE
[BUG] Doesn't work properly with material-ui Modal component

### ISSUE THREAD

**Issue by lednhatkhanh** [framer/motion#445]
**2. Describe the bug**

Motion doesn't work properly with Material-Ui Modal component. I follow the example of react-spring since there is no example of framer-motion in their docs: https://material-ui.com/components/modal/#transitions

The problem is, the Material-UI backdrop component doesn't get cleared after closing the modal, so I can't click the button again. After a while debugging, I see that the `open` props passed to the `MotionWrapper` component is always true, but it works if I change to use react-spring

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/framer-motion-material-ui-modal-jnzy9

**4. Steps to reproduce**

1. Click 'Open Modal' button
2. Click the backdrop to close the modal
3. The button can't be clicked again, the modal doesn't get closed

**5. Expected behavior**

The modal get closed after the animation ends

**Comment by mattgperry** [comment]
The `onAnimationComplete` callback is never updated because you've removed the component with the `boolean`. You have to point the callback to a piece of shared memory that persists throughout the parent's lifecycle, like so: https://codesandbox.io/s/framer-motion-material-ui-modal-forked-ymhhp?file=/src/MotionModal.js:853-892
