### ISSUE TITLE
[BUG] staggerChildren doesn't work if you try to add 'animate' or 'initial' attr on children.

### ISSUE THREAD

**Issue by tirli** [framer/motion#536]
**1. Describe the bug**

I'm trying to use `staggerChildren` and it works but only until I add `animate` or `initial` attribute on children.

**3. Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/variants-nhfgw?file=/src/Example.tsx

**4. Steps to reproduce**
1. Open codesandbox
1. Reload page inside iframe
1. Circles don't stagger
1. Remove `animate` and `initial` props
1. It works

**5. Expected behavior**

Children props should not affect `staggerChildren` behavior

**6. Environment details**

Chrome 81.0.4044.138

**Comment by jthrilly** [comment]
These two bugs are interesting and IMO related conceptually.

`<AnimatePresence>` requires `initial` and `animate` on a motion component, but `staggerChildren` expressly won't work with them. This latter point is (sort of) documented in the sense that `staggerChildren` uses variants, and variants stop propagating when a child element has an `animate` prop: https://www.framer.com/api/motion/animation/#variants

I believe `<AnimatePresence>` is behaving fairly consistently with the API/docs (docs show it used with these props: https://www.framer.com/api/motion/animate-presence/), but whether `initial` and `animate` should conceptually be required on motion components is a separate concern best discussed in #537.  

I think the real issue here is that because `staggerChildren` is tied to variants, you cannot use it in combination with `<AnimatePresence>`. This seems quite inflexible. I agree with @tirli that it would be ideal if `staggerChildren` could propagate through motion components without using variants. 

Is that feasible?

**Comment by mattgperry** [comment]
Adding initial/animate starts a new animation so the "staggering" doesn't propagate. As @jthrilly says this is in part because staggerChildren doesn't propagate without variants, so likewise it doesn't propagate through components that are considered different animations.

This is partly a technical thing but it's also because with variants we can infer some level of intent. If you set `animate` you're basically saying "from here, animate...", so with a variant we carry this intent through the tree until we hit a component that sets its own `animate`.
