### ISSUE TITLE
[BUG] modifyTarget is causing a jumpy transition 

### ISSUE THREAD

**Issue by Elia-Darwish** [framer/motion#577]
**2. Describe the bug**

Using modifyTarget on a Draggable's element dragTransition is resulting in a jumpy behavior, this is happening on drag end where it seems like the element is skipping a bit ahead!

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/polished-waterfall-u037u?file=/src/App.js

**5. Expected behavior**

a smooth page transition like animation like the one available to use in Framer

**6. Video or screenshots**

here is a video that shows how it is behaving:
https://res.cloudinary.com/elia-d/video/upload/v1590566454/Screen_Recording_2020-05-27_at_09.49.06.mov

**Comment by stokesman** [comment]
This could be fixed with an update of the Popmotion dependency. I've experimented with couple ways to remove any potential blocks of that update. First, #596 was to make possible a switch to Popmotion ^8.7.3 without bundle size increases. Second, I made [a branch of Popmotion](https://github.com/stokesman/popmotion/tree/8omega) to work as a publishable beta-9. I would have made a PR with that branch to discuss but there's not a reasonable branch to make the request against (feature/pure-9 is well ahead).
