### ISSUE TITLE
[FEATURE] Ship without polyfills (tslib) 

### ISSUE THREAD

**Issue by seivan** [framer/motion#584]
Edit: Technically I'd consider this a bug, because your `Rollup` plugin with Typescript forces `emitHelpers: true` which shoves `tslib` into the final bundle and from my impression the author of said library has no intention of changing that. 

**Is your feature request related to a problem? Please describe.**
The library is shipping with `tslib` which adds to the bundle sizes and duplicates existing polyfils on the consumer side (application).
This can't be tree-shaked and is `3.73kb` that can be shaved off.
This constitutes `4.3%` of `motion` and `9%` of `popmotion`.

Though I am not sure if you would have to do it for the dependencies that seem to have the same issue. 

**Describe the solution you'd like**
Ship without any polyfills as those belongs on the consumer side.
An example of this is something like `ObjectAssign` which comes from`core-js`, `React` and now this library via `tslib`.

**Describe alternatives you've considered**
Excluding `ObjectAssign` from `core-js` and `React` via some build magic, but it seems weird that it should come from an animation library. 

You could do this by adding `exclude: ["tslib"]` to your `CJS`and `ES` builds.

**Comment by mattgperry** [comment]
I'll take a look at this now!

**Comment by mattgperry** [comment]
Looking into it, using tslib was precisely so we didn't need to include the helpers directly in our various libraries. As far as I can tell we don't get a choice in how Typescript transpiles code like spread operators so helpers need to be included one way or the other.

**Comment by seivan** [comment]
@mattgperry I don't think I understood, when you say "various" libraries, do you mean other packages that rely on motion? 
Why would they need it? They would just be used by an application that already has those.

**Comment by mattgperry** [comment]
Sorry I mean all the libraries motion depends on, like Popmotion. They all share the same tslib. And any Typescript projects using Motion will also share it.

Build systems typically don’t transpile libraries which is why all the ones you mentioned have their own polyfill for es6 features. It might be that this has changed in the last year?

**Comment by seivan** [comment]
> Build systems typically don’t transpile libraries which is why all the ones you mentioned have their own polyfill for es6 features, as they ship pre-transpiled. It might be that this has changed in the last year?
No, you're correct, for libraries. 
Applications would and should do it.

>  They all share the same tslib. And any Typescript projects using Motion will also share it.
No, that's the issue. It's added next to my existing polyfills.
You don't need to distribute it. 

Its been a while since I looked at this, and I am not sure what changes you guys have done, could be that it's a moot point at this time, so I'm going to check later and get back to you, but as far as I remember, I had several additions of them and it was a bit unnecessary. Your distributed modules don't really need them.

**Comment by mattgperry** [comment]
Thing is these aren't really "polyfills" as such, they're a result of the transpilation. It isn't like adding a polyfill for `Map` where there is a standard API for `Map` and you can use his polyfill or her polyfill and it doesn't matter which you end up using. Typescript will transpile, for example, destructuring in a particular way which often uses a helper function with a name like `__apply` or whatever. `__apply` isn't a standard that you can just swap for your own "polyfill".

To mitigate the impact of this transpiled code, Typescript allows TS modules to refer to `tslib`, so they can share these functions amongst themselves rather than duplicating the code. Many TS libraries out there probably just bury this added weight by not using the `importHelpers` option that enables this. 

The only way I see to fix this would be to export Typescript as transpiled into a more modern `target`, this way it'd leave things like `class` and destructuring alone. But I'd probably receive a lot more bug reports when this syntax ships directly to end users.
