### ISSUE TITLE
[BUG] Layout distortion correction doesn't work in response to child changes

### ISSUE THREAD

**Issue by dminkovsky** [framer/motion#637]
Please have a look at https://codesandbox.io/s/framer-motion-2-layout-animations-pei0x?file=/src/App.js

Based on the docs and other examples, you would expect this to work. However, it does this:

![ezgif-4-2224cfaf3dda](https://user-images.githubusercontent.com/218725/87727327-c6a1d700-c78e-11ea-806f-bbfb1be406a9.gif)

Oddly, when you change `layout={true}` to `layout={false}` on the inner `motion.div` that's supposed to perform the correction, despite what the docs say (that `layout={true}` should be set to perform the correction), the functionality starts working:

![ezgif-4-39ff8ac09309](https://user-images.githubusercontent.com/218725/87727261-a07c3700-c78e-11ea-9a38-852e4e5c1ac7.gif)

Stranger still: if you save `layout={false}` and reload, it stops working. This behavior is consistent for me in Chrome and FF.

**Comment by InventingWithMonster** [comment]
Hmm this is a tricky one. By providing the `layout` prop to both elements they both perform layout animations. Because the text content is changing in the child, this looks like distortion, but in essence this is the correct behaviour. You can test this by popping it out of the parent - it still distorts in the exact same way.

Perhaps what is needed is a setting that doesn't perform any layout animations and allows for the instant switching of layout but maintains the component's scale, something like:

```jsx
<motion.div layout="preserve" />
```

**Comment by eschaefer** [comment]
> `<motion.div layout="preserve" />`

TypeScript gave me feedback that `"preserve"` wasn't a valid value for `layout`, but `"position"` worked! 

Was experiencing a similar distortion issue and `<motion.div layout="position" />` fixed it.

**Comment by InventingWithMonster** [comment]
@eschaefer Sorry yeah I landed on position. Glad that fixed it for you!
