### ISSUE TITLE
[FEATURE] Support percentage values for layout projection transforms

### ISSUE THREAD

**Issue by IvanIsakof** [framer/motion#648]
Hello,

I have sticked notifications animated with Framer, for example: 
https://codesandbox.io/s/framer-motion-notifications-jvsk2

add a few more notications then delete them, and you'll see notification disappears incorrectly. Only opacity is animated, x should be animate too `exit={{ opacity: 0, x: "100%" }}`.
Experimentaly I found that if I use absolute values for x `exit={{ opacity: 0, x: 300 }}` everything works correctly.

**Comment by InventingWithMonster** [comment]
The reason for this is layout animations incorporate transforms directly onto the layout projection box itself. Currently it only supports pixel amounts. I think it would be quite possible to support percentages too.

For my future reference: This should be relative to the size the element is currently being projected at rather than its "real" layout size, as this will scale smoothly with layout animations vs jumping when a component changes size.

**Comment by IvanIsakof** [comment]
@mattgperry Hello! I still cannot use version 2x because it doesn't support percent values! Looking forward you add percent values support.
Thanks in advance and for great job on version 2x

**Comment by mattgperry** [comment]
I took a little spike on this this afternoon and it's a little more difficult than I'd hoped. Reason being to resolve the percentages you need the layout of any element with a percentage transform anywhere up the tree. Maybe I'll take another run when I've got some more time.

**Comment by mattgperry** [comment]
Closing as `wontfix` to set expectations.

It's still possible this could be implemented, but it's unlikely to happen unless we need the functionality inside Framer.

**Comment by alexsafayan** [comment]
does anyone have a workaround?
