### ISSUE TITLE
[BUG] Style changes while dragging with layout transition will displace dragging object

### ISSUE THREAD

**Issue by leodr** [framer/motion#685]
**2. Describe the bug**

I want to make a button that can be dragged in one of the 4 screen corners. I use a motion.div with layout and drag and reposition it based on the current dragging position in onDrag.
But when I change the x and y transform while dragging the button snaps to a different spot (is not under the cursor anymore).

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/brave-williamson-7mib8?file=/src/App.js

**4. Steps to reproduce**

1. Drag the button in any of the corners.

**5. Expected behavior**

I would expect the button to stay under the cursor the entire time and after releasing it it would animate back to one of the 4 screen corners because of the dragConstraints.

**6. Video or screenshots**

![bug](https://user-images.githubusercontent.com/39763575/89013116-9e2fe600-d313-11ea-9bbc-a18616e30e59.gif)

**7. Environment details**

Latest Chrome on Windows 10.

**Comment by InventingWithMonster** [comment]
Hey @leodr 

The x/y transform is currently additive on top of the layout projection. Which is why the ball animates in from off-page.

What you probably want to do is, rather than changing layout using x/y transforms, is *actually* change the layout of the DOM. For instance you could use `top`/`left`/`right`/`bottom`. Or make the container a flexbox and change `align-items` etc. Because you have `drag layout` and `dragConstraints` applied, when you release the ball it should animate to its new layout.

This will also ensure your page remains responsive.

**Comment by leodr** [comment]
Thanks for the tip @InventingWithMonster, it worked!

Here's a working example for anyone encountering this in the future
https://codesandbox.io/s/framer-motion-button-dragging-bug-fixed-i2rbc
