### ISSUE TITLE
[BUG] whileHover stops working with transition type spring

### ISSUE THREAD

**Issue by stolinski** [framer/motion#739]
**2. Describe the bug**

whileHover stopped working recently when applying transition type spring. This worked with prior versions of Framer Motion, but I haven't dug into when exactly it stopped working.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/react-blank-starter-forked-6lh57?file=/src/App.js

**4. Steps to reproduce**

Hover over the box in the example. Comment out type: "spring" to see animation work.

**5. Expected behavior**

whileHover to animate

**Comment by InventingWithMonster** [comment]
Ah what's probably happening here is that this never "worked" but it didn't used to break 😅.

Because the values are defined as keyframes, this used to force an animation to use a keyframes animation. I think there's a bug in Popmotion 9 where you can force an animation to be spring by defining `type: "spring"`, even if the values are defined as keyframes. For now I'm going to fix this by forcing the animation to keyframes if `to` is an array, but I can see a future where you could use a keyframes with spring.

**Comment by stolinski** [comment]
I had that discussion in my mind about how this could possibly work as a spring animation with keyframes. Def a leftover from some old code that just happened to stop working on this update. Thanks for the explanation Matt.
