### ISSUE TITLE
Spring with scale is not working as expected [BUG]

### ISSUE THREAD

**Issue by anim8rDev** [framer/motion#749]
The following codesandbox example will smoothly animate scale when you hover.  However, if you switch from version 2.4.3 to a recent version of Framer, it is no longer smooth.   Animation seems to almost end abruptly.   And in some versions, the scale will pop to some wildly scaled values well outside of 1.2 and .8.

https://codesandbox.io/s/framer-motion-gesture-animations-forked-zfdv0?file=/src/Example.tsx

**Comment by InventingWithMonster** [comment]
So you can play with restSpeed and restDelta options to find a smoother behaviour but I’ll take a look at this and fix the defaults for these scale values, good find thanks

**Comment by anim8rDev** [comment]
That fixed it.  Thanks!

**Comment by Pinpickle** [comment]
@mattgperry have you had a chance to look into this? It appears to still be the case, even in the v5 beta.

Going through the versions of framer-motion, this appeared to happen in the change from v2.5.2 to v2.5.3

The only significant change was upgrading to popmotion v6.0.0-rc6. While I haven't dug into it too deeply, this commit seems a likely cause: https://github.com/Popmotion/popmotion/commit/9d8e45bf196ed6acded156519cebf2726878cca1 where the default `restSpeed` changes from 0.005 to 10.

This is pretty frustrating as by default, all scale animations don't seem natural (which is why we use framer-motion in the first place).

Is there a workaround to change the defaults for all transitions?

**Comment by JorensM** [comment]
This happened to me, what I found out is that you have to set `stiffness` to a pretty high value like 500-1000 for the spring effect to be visible
