### ISSUE TITLE
Anyone know if you lose SEO by doing <AnimatePresence> for page transitions?

### ISSUE THREAD

**Issue by joshbedo** [framer/motion#850]
Just wondering if anyone has explored this but does animating page transitions with <AnimatePresence /> cause you to lose all SEO. Just thinking that the pages might not be visible to crawlers if the initial opacity is set to 0. But kind of assuming things I guess.. not sure. TIA

**Comment by nagman** [comment]
I don't agree, as the opacity is set on server-side. So if you load your page with javascript disabled, you won't be able to see any of your content. So I think it can have some impact on the SEO. I've done a lot of searches on this, concerning Google indexing initially hidden content, but I've not found anything relevant yet.

**Comment by mattgperry** [comment]
It’s a bit of a black box to be honest. Google does run javascript so it should be the case that they detect that content has been animated in. If not, they do mark down opacity: 0 content so it might be worth checking to see if it’s the initial page load or not and only perform an animation for subsequent page loads.

**Comment by nagman** [comment]
But how would you do that with framer-motion?
If you want simple pages transitions (like fade-out/fade-in), you need to specify `initial` on your `motion` elements.
And if you remove it, you won't be able to see the fade-in on next page loading.

To allow non-javascript users to use the website, framer-motion should only apply in a `useEffect` hook, so that SSR frameworks like next.js won't apply `opacity: 0` on the first render.

**Comment by mattgperry** [comment]
You could dynamically set initial based on whether this is the initial page or subsequent pages.
