### ISSUE TITLE
[FEATURE] animate to variant onHoverEnd

### ISSUE THREAD

**Issue by hazem-osama** [framer/motion#910]
**Is your feature request related to a problem? Please describe.**
I want to make an animation where if I hover a component it scales and when I leave the hover it should disappear with an opacity of 0.
the problem is from my understanding, I can only animate between `animate` and `whileHover` variants, for example
```jsx
<motion.div animate="normal" whileHover="scale" />
```
in this component I can only go from `normal` and `scale` variants

**Describe the solution you'd like**
I would like to be able to set a variant to animate to when I leave the hover state
```jsx
<motion.div animate="normal" whileHover="scale" onHoverEnd="disappear" />
```

**Comment by oielbanna** [comment]
Just a suggestion here but have you tried using `onHoverStart/End` with the `useAnimation` hook instead of `whileHover`? you can do something like

`
const controls = useAnimation()
<motion.div 
animate={controls} 
initial="normal"
onHoverStart={() => controls.start("scale")} 
onHoverEnd={() => controls.start("disappear")}
 />
`

**Comment by hazem-osama** [comment]
can I do something like this?
```jsx
onHoverEnd={async () => {
	await controls.start('disappear')
	await controls.start('normal')
}}
```

**Comment by hazem-osama** [comment]
Found out that you could 😄, thanks @oielbanna, will close this issue
